### ISSUE TITLE
[ERROR:src/chain.c:70]: invalid chain data

### ISSUE THREAD

**Issue by chiroTester** [rvaser/sift4g#11]
We are attempting to built a SIFT database (https://sift.bii.a-star.edu.sg/sift4g/SIFT4G_codes.html) using the sift4g algorithm on our Linux supercomputing cluster. However, we have hit the following difficult-to-parse error once it reaches what appears to be the sift4g portion of database building. Could you please advise us on the best way forward? Let us know what additional information you need.

done making the fasta sequences
start siftsharp, getting the alignments
/home/staff/chiroTester/tools/SIFT/sift4g/bin/sift4g -d /home/staff/chiroTester/ref_files/uniref90.fasta.gz -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
[ERROR:src/chain.c:70]: invalid chain data

**Comment by rvaser** [comment]
Hello,
gziped files are unfortunately not supported. Try unzipping the `uniref90.fasta.gz` database and run again.

Best regards,
Robert

**Comment by xiangqing111** [comment]
Hi, I have extracted my files but I am experiencing a similar problem.* processing database part 90 (size ~0.25 GB): 72.50/100.00% *
* processing database part 90 (size ~0.25 GB): 75.00/100.00% *
* processing database part 90 (size ~0.25 GB): 77.50/100.00% *
* processing database part 90 (size ~0.25 GB): 80.00/100.00% *
* processing database part 90 (size ~0.25 GB): 82.50/100.00% *
* processing database part 90 (size ~0.25 GB): 85.00/100.00% *
* processing database part 90 (size ~0.25 GB): 87.50/100.00% *
* processing database part 90 (size ~0.25 GB): 90.00/100.00% *
* processing database part 90 (size ~0.25 GB): 92.50/100.00% *
* processing database part 90 (size ~0.25 GB): 95.00/100.00% *
* processing database part 90 (size ~0.25 GB): 97.50/100.00% *
* processing database part 90 (size ~0.25 GB): 100.00/100.00% *
[ERROR:src/chain.c:101]: chain is empty after encoding, see scorerEncode function
