### ISSUE TITLE
VCF File input error

### ISSUE THREAD

**Issue by hrwaik** [rvaser/sift4g#12]
Hello,

I am looking to use SIFT on some E coli genomes that I've aligned but I keep getting the error:

Chromosome	WithSIFT4GAnnotations	WithoutSIFT4GAnnotations	Progress
ERROR! Input VCF file should contain at least 8 columns. See line: 
Chromosome,70289,.,C,A,100,0,*,TYPE=SUBSTITUTE

This is even though my vcf file has 8 columns (I added in a dummy column so there are actually 9, 8 of the original vcf file) and follows the layout of the example vcf file in the supplementary of the nature protocols paper. I get this error when using either the GUI or running it in terminal. 

Here's a head of my vcf file:
#CHROM,POS,ID,REF,ALT,QUAL,Y,FILTER,INFO
Chromosome,70289,.,C,A,100,0,*,TYPE=SUBSTITUTE
Chromosome,366519,.,G,A,100,1,*,TYPE=SUBSTITUTE
Chromosome,503429,.,C,T,100,2,*,TYPE=SUBSTITUTE
Chromosome,705013,.,A,G,100,3,*,TYPE=SUBSTITUTE
Chromosome,1633629,.,T,C,100,4,*,TYPE=SUBSTITUTE
Chromosome,1633924,.,C,A,100,5,*,TYPE=SUBSTITUTE
Chromosome,1652331,.,T,C,100,6,*,TYPE=SUBSTITUTE
Chromosome,2173362,.,CCC,C,100,7,*,TYPE=DELETE
Chromosome,2731078,.,C,A,100,8,*,TYPE=SUBSTITUTE

Thanks for your help!

**Comment by rvaser** [comment]
Hello,
I think that this error is tied either with SIFT4G_Annotator or SIFT4G_Create_Genomic_DB repository. @pauline-ng, could you please help with this issue?

Best regards,
Robert

**Comment by pauline-ng** [comment]
@hrwaik 

Sorry for the delay, this Github notification went to my spam box!

A VCF file is typically tab-delimited. Your file appears to be comma-delimited?
Please post your issues here: https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB

**Comment by samson-olofinsae** [comment]
Hi hrwaik, I hope you have resolved the issue with your SIFT run.  
VCF is tab-delimited; the CSV format you used to as input VCF might be the cause of the issue.
You can transform your original vcf and still maintain the tab-delimited format of it by running the code:

cat original_vcf_file | grep -v "##" > output_vcf_file          # The file extension of your output file corresponds to the extension of your input file (.vcf or vcf.gz)

You can then use the transformed output vcf file as input for your SIFT run - of course, while keeping the Chr column as "Chromosome" just as you already did!

**Comment by samson-olofinsae** [comment]
Hi hrwaik,  The code should be:

zcat original_vcf_file | grep -v "##" > output_vcf_file # if file extension is .gz
