### ISSUE TITLE
Questions about the protein database

### ISSUE THREAD

**Issue by apredeus** [rvaser/sift4g#14]
Dear Robert, 

I apologize in advance if this is not a good place to ask these questions. 

I was wondering which protein database is the most appropriate for annotation of missense variants in a bacterium? I've ran variant effect prediction on approx. 30k missense mutations in 4k genes. I've tried swissprot and uniref 90 as reference databases. The final stats are like this

> Swissprot:   20574 DELETERIOUS   8453 TOLERATED
> UniRef 90:   13215 DELETERIOUS 15810 TOLERATED

I am somewhat unsure what are the numbers in `sift4g` output. Seems like they are a bit different from classical sift? 

> P95S	DELETERIOUS	0.00	3.74	7	8
> A85T	DELETERIOUS	0.03	3.74	7	8

From what I understand, last 1 or 2 numbers is the number of reference sequences the prediction is based on. Is the number capped at 400, and how are 400 selected? I've also seen quite a few sequences that are predicted based on 1 sequence - is that OK? 

Thank you!

**Comment by rvaser** [comment]
Hi Alex,
I am not sure which database to use, I think @pauline-ng might know the answer.

Regarding the output, the last number is the number of alignments used for the query, while the number before is the number of sequences having a match/mismatch at this position (@pauline-ng please correct me if I am wrong). 

As I recall, the top 400 alignments are scanned through from the best scoring to the least (with regards to the e-value) and are added iteratively until the median conservation threshold is reached. I would say prediction based only on 1 sequence is not reliable (@pauline-ng please correct me if I am wrong).

Best regards,
Robert

**Comment by pauline-ng** [comment]
Hi Alex,

The last number is in the # of sequences in the protein alignment; the 2nd to last number is the # of sequences at that position of prediction (so it's always <= the last column.)

If you see a few sequences with 1 sequence for prediction, I would not rely on this. 

Here are some basic rules:
If it's predicted tolerated, take the prediction.
If it's predicted deleterious, I would only have believe it if 4th column is < 3.25.  The 4th column is the sequence diversity of the sequences in the alignment -- if it's too high that means the sequences in the protein alignment are not diverse enough and hence there is less confidence in the prediction.

Thanks,
Pauline

**Comment by apredeus** [comment]
Wow, thank you very much for the quick and very helpful response! 

@pauline-ng one last question: is it assumed that the protein database is clustered for redundancy, e.g. like uniref 90 or nr? There's a (relatively) new database that NCBI is using for prokaryotic annotation, called Identical Protein Groups, which makes for quite excellent collection of bacterial proteins. However I'm concerned that the sequences might be too close to each other and result in low "sequence diversity" parameter for `sift4g`.

Thanks again!

**Comment by pauline-ng** [comment]
SIFT's sequence diversity is weighted (it takes into account closely related sequences.)
