### ISSUE TITLE
Questions on test_data

### ISSUE THREAD

**Issue by wangnan9394** [rvaser/sift4g#15]
Hi,
I have a question on test_data. When i compile the sift4g on my ubuntu and test on test_data.
the command "./bin/sift4g -q ./test_files/query.fasta --subst ./test_files/ -d ./test_files/sample_protein_database.fa" always showed
```
** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)
```
But the command "./bin/sift4g -q ./test_files/query.fasta -d ./test_files/sample_protein_database.fa" seems work.
Could you help me?
I talked with @pauline-ng ，because I tried to build a database using SIFT4G_Create_Genomic_DB. The same error seems happend again.

Bests,
Nan

**Comment by pauline-ng** [comment]
Hi Nan,

Please list all the files inside the directory ./test_files

**Comment by rvaser** [comment]
Hi Nan,
please make sure you have at least gcc4.9 when compiling SIFT4G, otherwise regex won't work properly.

Best regards,
Robert

**Comment by wangnan9394** [comment]
Hi Robert，
Thank you so much.
I found my gcc version is 4.8.6. Although the compilation appear to be successful and it was not work. Now I start to build using conda and over this problem.
 I really appreciate it.

regards,
Nan
