### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by jaholliday** [rvaser/sift4g#16]
Hello,

I'm getting an error when trying to compile sift4g on a Mac running Catalina. Any ideas what could be going on? See below the result of 'gcc -v' and 'make' below that

Thanks!

jah1$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

----------------------------

h80ad4bb7:sift4g jah1$ make
>>> vendor/swsharp <<<
[CORE] swsharp
[CP] src/nw_find_score_gpu.cu
[CC] src/thread.c
[CC] src/constants.c
[CP] src/ov_end_data_gpu.cu
[CC] src/reconstruct.c
[CC] src/ssw/ssw.c
[CC] src/sse_module.c
[CC] src/database.c
[CC] src/post_proc.c
[CP] src/score_database_gpu.cu
[CP] src/score_database_gpu_short.cu
[CP] src/nw_linear_data_gpu.cu
[CC] src/align.c
[CC] src/utils.c
[CC] src/chain.c
[CP] src/hw_end_data_gpu.cu
[CC] src/threadpool.c
[CC] src/alignment.c
[CC] src/db_alignment.c
[CP] src/sw_end_data_gpu.cu
[CP] src/evalue.cu
[CP] src/score_database_gpu_long.cu
[CP] src/cuda_utils.cu
[CP] src/ov_find_score_gpu.cu
[CP] src/swimd/Swimd.cpp
[CC] src/pre_proc.c
[CC] src/scorer.c
[CP] src/gpu_module.cu
[CC] src/cpu_module.c
[AR] ../lib/libswsharp.a
[CP] ../include/swsharp/align.h
[CP] ../include/swsharp/alignment.h
[CP] ../include/swsharp/chain.h
[CP] ../include/swsharp/constants.h
[CP] ../include/swsharp/cpu_module.h
[CP] ../include/swsharp/cuda_utils.h
[CP] ../include/swsharp/database.h
[CP] ../include/swsharp/db_alignment.h
[CP] ../include/swsharp/evalue.h
[CP] ../include/swsharp/gpu_module.h
[CP] ../include/swsharp/post_proc.h
[CP] ../include/swsharp/pre_proc.h
[CP] ../include/swsharp/reconstruct.h
[CP] ../include/swsharp/scorer.h
[CP] ../include/swsharp/swsharp.h
[CP] ../include/swsharp/thread.h
[CP] ../include/swsharp/threadpool.h
[CP] ../swsharpwin/swsharp/chain.h
[CP] ../swsharpwin/swsharp/error.h
[CP] ../swsharpwin/swsharp/utils.h
[CP] ../swsharpwin/swsharp/score_database_gpu_short.h
[CP] ../swsharpwin/swsharp/ssw/ssw.h
[CP] ../swsharpwin/swsharp/align.h
[CP] ../swsharpwin/swsharp/score_database_gpu_long.h
[CP] ../swsharpwin/swsharp/db_alignment.h
[CP] ../swsharpwin/swsharp/threadpool.h
[CP] ../swsharpwin/swsharp/alignment.h
[CP] ../swsharpwin/swsharp/swsharp.h
[CP] ../swsharpwin/swsharp/cpu_module.h
[CP] ../swsharpwin/swsharp/scorer.h
[CP] ../swsharpwin/swsharp/pre_proc.h
[CP] ../swsharpwin/swsharp/reconstruct.h
[CP] ../swsharpwin/swsharp/constants.h
[CP] ../swsharpwin/swsharp/thread.h
[CP] ../swsharpwin/swsharp/database.h
[CP] ../swsharpwin/swsharp/sse_module.h
[CP] ../swsharpwin/swsharp/cuda_utils.h
[CP] ../swsharpwin/swsharp/swimd/Swimd.h
[CP] ../swsharpwin/swsharp/evalue.h
[CP] ../swsharpwin/swsharp/post_proc.h
[CP] ../swsharpwin/swsharp/gpu_module.h
[CP] ../swsharpwin/swsharp/nw_find_score_gpu.cu
[CP] ../swsharpwin/swsharp/thread.c
[CP] ../swsharpwin/swsharp/constants.c
[CP] ../swsharpwin/swsharp/ov_end_data_gpu.cu
[CP] ../swsharpwin/swsharp/reconstruct.c
[CP] ../swsharpwin/swsharp/ssw/ssw.c
[CP] ../swsharpwin/swsharp/sse_module.c
[CP] ../swsharpwin/swsharp/database.c
[CP] ../swsharpwin/swsharp/post_proc.c
[CP] ../swsharpwin/swsharp/score_database_gpu.cu
[CP] ../swsharpwin/swsharp/score_database_gpu_short.cu
[CP] ../swsharpwin/swsharp/nw_linear_data_gpu.cu
[CP] ../swsharpwin/swsharp/align.c
[CP] ../swsharpwin/swsharp/utils.c
[CP] ../swsharpwin/swsharp/chain.c
[CP] ../swsharpwin/swsharp/hw_end_data_gpu.cu
[CP] ../swsharpwin/swsharp/threadpool.c
[CP] ../swsharpwin/swsharp/alignment.c
[CP] ../swsharpwin/swsharp/db_alignment.c
[CP] ../swsharpwin/swsharp/sw_end_data_gpu.cu
[CP] ../swsharpwin/swsharp/evalue.cu
[CP] ../swsharpwin/swsharp/score_database_gpu_long.cu
[CP] ../swsharpwin/swsharp/cuda_utils.cu
[CP] ../swsharpwin/swsharp/ov_find_score_gpu.cu
[CP] ../swsharpwin/swsharp/swimd/Swimd.cpp
[CP] ../swsharpwin/swsharp/pre_proc.c
[CP] ../swsharpwin/swsharp/scorer.c
[CP] ../swsharpwin/swsharp/gpu_module.cu
[CP] ../swsharpwin/swsharp/cpu_module.c
[MOD] swsharpn
[CC] src/main.c
[LD] swsharpn
[CP] ../bin/swsharpn
[CP] ../swsharpwin/swsharpn/main.c
[MOD] swsharpp
[CC] src/main.c
[LD] swsharpp
[CP] ../bin/swsharpp
[CP] ../swsharpwin/swsharpp/main.c
[MOD] swsharpnc
[CC] src/main.c
[LD] swsharpnc
[CP] ../bin/swsharpnc
[CP] ../swsharpwin/swsharpnc/main.c
[MOD] swsharpdb
[CC] src/main.c
[LD] swsharpdb
[CP] ../bin/swsharpdb
[CP] ../swsharpwin/swsharpdb/main.c
[MOD] swsharpout
[CC] src/main.c
[LD] swsharpout
[CP] ../bin/swsharpout
[CP] ../swsharpwin/swsharpout/main.c
>>> sift4g <<<
[CP] src/database_search.cpp
[CP] src/utils.cpp
[CP] src/sift_prediction.cpp
[CP] src/select_alignments.cpp
[CP] src/database_alignment.cpp
[CP] src/sift_scores.cpp
src/sift_scores.cpp:242:23: error: implicit instantiation of undefined template
      'std::__1::basic_stringstream<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
    std::stringstream stream;
                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:139:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
src/sift_scores.cpp:280:35: error: implicit instantiation of undefined template
      'std::__1::basic_stringstream<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::stringstream ss(std::stringstream::in | std::stringstream::out);
                                  ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:139:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
src/sift_scores.cpp:280:59: error: implicit instantiation of undefined template
      'std::__1::basic_stringstream<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::stringstream ss(std::stringstream::in | std::stringstream::out);
                                                          ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:139:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
src/sift_scores.cpp:280:27: error: implicit instantiation of undefined template
      'std::__1::basic_stringstream<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::stringstream ss(std::stringstream::in | std::stringstream::out);
                          ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:139:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
4 errors generated.
make[1]: *** [obj/sift_scores.o] Error 1
make: *** [sift4g] Error 2

**Comment by rvaser** [comment]
Hello,
try adding `#include <sstream>` at the beginning of file `src/scores.cpp` and recompile.

Sorry for my late reply!
Best regards,
Robert

**Comment by jaholliday** [comment]
Thanks. That did it. I get an executable that seems to work, though I did get this warning during compilation. Not sure if it matters.

[CP] src/sift_scores.cpp
src/sift_scores.cpp:24:20: warning: unused variable 'kMaxSequences'
      [-Wunused-const-variable]
constexpr uint32_t kMaxSequences = 400;
                   ^
src/sift_scores.cpp:28:18: warning: unused variable 'LOCAL_QIJ_RTOT'
      [-Wunused-const-variable]
constexpr double LOCAL_QIJ_RTOT = 5.0;
                 ^
2 warnings generated.
[CP] src/hash.cpp
src/hash.cpp:16:20: warning: unused variable 'kProtMaxValue'
      [-Wunused-const-variable]
constexpr uint32_t kProtMaxValue = 25;

**Comment by rvaser** [comment]
Those are indeed unused variables, nothing to worry about.
