### ISSUE TITLE
Sift4g stuck up without error report

### ISSUE THREAD

**Issue by huangl-CAU** [rvaser/sift4g#18]
Dear Robert,
I met a weird problem when I use sift4g.
The program stuck up when I run a command like that
"`home/sift4g/bin/sift4g -d PATH1/uniref90.fasta -q PATH2/all_prot.fasta --subst PATH3/subst --out PATH4/SIFT_predictions --sub-results -t 32` "   , As a part of "make-SIFT-db" pipeline.
No CPU time was assigned to sift4g,  when the program runs to  the  "Selecting alignments" sub-step. This state has lasted for almost two days.

The log file and program state are as follow.
![image](https://user-images.githubusercontent.com/58922355/118359435-08b9c600-b5b6-11eb-91c5-d9b50a2c6adc.png)
![image](https://user-images.githubusercontent.com/58922355/118359561-9c8b9200-b5b6-11eb-9065-cd656b3d4aef.png)

pleas let me informed if there is any solution for this issue ,thanks for your time.

best wish
Huang Liang

**Comment by rvaser** [comment]
Hi Huang,
which commit/version of SIFT4G are you using?

Best regards,
Robert

**Comment by huangl-CAU** [comment]
I cannot find the detail info about the version of SIFT4G, the program was compiled with "git-clone & make" command about several days ago.

And there is some information may be used as clues.
1. the program works well with test data.
2. I picked up two proteins of the unfinished database(what's is mentioned in the initial question)  and fed it into the SIFT4G with the corresponded subset files. The program finished appropriately.
3.  In the  initial question,the was only a " alignments.txt" in the  SIFT_predictions fold which contain the same proteins num with the "all_prot.fasta "
4.  There are some subset file with zero file size,which not contain in the "all_prot.fasta"

So may there be something wrong with the protein files?

**Comment by huangl-CAU** [comment]
I cannot find the detail info about the version of SIFT4G, the program was compiled with "git-clone & make" command about several days ago.

And there are some informations may be used as clues.

1. The program works well with the test data you provided.
2. I picked up two proteins of the unfinished database(what's is mentioned in the initial question) and fed it into  SIFT4G with the corresponded subset files. The program finished appropriately.
3. In the initial question,only the  " alignments.txt"  generated in the SIFT_predictions fold which contain the same protein num with the "all_prot.fasta " file
4. There are some subset files with zero file size, which not contain in the "all_prot.fasta" file

So may there be something wrong with the protein file?

thanks again
Huang Liang

**Comment by rvaser** [comment]
You can get the commit with `git log`, but if you cloned recently you have the latest version. There was a bug some time ago tied with zero alignments found for a protein, but I think this should have been fixed. Can you perhaps share the data so I can investigate?

**Comment by cfz1998** [comment]
> Dear Robert, I met a weird problem when I use sift4g. The program stuck up when I run a command like that "`home/sift4g/bin/sift4g -d PATH1/uniref90.fasta -q PATH2/all_prot.fasta --subst PATH3/subst --out PATH4/SIFT_predictions --sub-results -t 32` " , As a part of "make-SIFT-db" pipeline. No CPU time was assigned to sift4g, when the program runs to the "Selecting alignments" sub-step. This state has lasted for almost two days.
> 
> The log file and program state are as follow. ![image](https://user-images.githubusercontent.com/58922355/118359435-08b9c600-b5b6-11eb-91c5-d9b50a2c6adc.png) ![image](https://user-images.githubusercontent.com/58922355/118359561-9c8b9200-b5b6-11eb-9065-cd656b3d4aef.png)
> 
> pleas let me informed if there is any solution for this issue ,thanks for your time.
> 
> best wish Huang Liang

I have the same error! Could you tell me how to fix it? Thank you!

**Comment by rvaser** [comment]
Hello,
could you perhaps share your data so I can investigate what is causing the bug?

Best regards,
Robert

**Comment by pauline-ng** [comment]
Closed due to lack of activity.
