### ISSUE TITLE
 regex_error

### ISSUE THREAD

**Issue by yywyaoyaowu** [rvaser/sift4g#19]
Dear Robert
I met a error when I run sift4g test data .
"./bin/sift4g -q ./test_files/query.fasta --subst ./test_files/ -d ./test_files/sample_protein_database.fa"
** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped).
My gcc is gcc-7.3.0, which is gcc 4.9+. Do you know why?

when I construnct the database using "perl make-SIFT-db-all.pl -config test_files/candidatus_carsonella_ruddii_pv_config.txt --ensembl_download"

it says: Possible precedence issue with control flow operator at /usr/local/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.
done making single records template
making noncoding records file

start siftsharp, getting the alignments
/workdir/yw2326/have_check/SIFT/sift4g/bin/sift4g -d /workdir/yw2326/have_check/SIFT/PROTEIN_DB/uniref90.fasta -q /local/workdir/yw2326/have_check/SIFT/SIFT4G_Create_Genomic_DB/database_output/all_prot.fasta --subst /local/workdir/yw2326/have_check/SIFT/SIFT4G_Create_Genomic_DB/database_output/subst --out /local/workdir/yw2326/have_check/SIFT/SIFT4G_Create_Genomic_DB/database_output/SIFT_predictions --sub-results 
** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

**Comment by rvaser** [comment]
Hello,
the error is usually tied with gcc version less than 4.9. What does `g++ --version` print when you run it?

Best regards,
Robert

**Comment by yywyaoyaowu** [comment]
Hi
it print "g++ (GCC) 7.3.0", which is  gcc 4.9+.

Yaoyao

**Comment by rvaser** [comment]
Run `which g++` and try adding the path to https://github.com/rvaser/sift4g/blob/master/sift4g/Makefile#L1. Run `make clean` and `make`.

**Comment by wpf95** [comment]
> Run `which g++` and try adding the path to https://github.com/rvaser/sift4g/blob/master/sift4g/Makefile#L1. Run `make clean` and `make`.

i use conda install sift4g，also appear same issue ，so what can i do to resolve

**Comment by rvaser** [comment]
I would advise compiling from source and make sure you have a valid compiler version. Using the bioconda executable might not work due to SIMD instructions.
