### ISSUE TITLE
Sift4g usage question 

### ISSUE THREAD

**Issue by Chenglin20170390** [rvaser/sift4g#21]
Hi,  many thanks for developing such useful software.

   I have a question about how to use sift4g properly, as usual, we can make a sift4G database and annotate my vcf file to know the deleterious mutation within genes. However, we think this method will introduce reference bias since it is based on reference calling vcf file.  
     So, in our case, we assembly 4 haplotype  genomes for autotetraploid and make sift4G database for each haplotype genome, and then we mark deleterious mutation based on the file `chr1_gz` in the directory of  `name_sift_database`  with the command ` zcat  chr/$i/${i}_sift_database/chr${chr}_${hap}.gz |grep 'ref' |awk '$11<0.05 {print}' ` . Is it working for detecting deleterious mutation?

    For another question, we have compared the deleterious mutation of synteny genes within 4 genomes using up method, we have 23086 synteny genes for 4 genomes.
>4 genes with no deleterious mutation  9167
>4 genes with only 1 gene has deleterious mutation  1172
>4 genes with only 2 genes has deleterious mutation  1079
>4 genes with only 3 genes has deleterious mutation  1565
>4 genes with  4 genes have deleterious mutation  10103

   You can see that the 4 genes with  4 genes have the deleterious mutation have a dominant proportion, to our knowledge, for autotetraploid, 4 genes with 1/2/3 genes have deleterious may have dominant proportion. Do you have any suggestions for us to compare the deleterious mutations within autotetraploid?
   
   many thanks for your help

**Comment by pauline-ng** [comment]
Hi,

Hmm....interesting. Is it possible the list of 10,103 are genes that are in superfamilies? So these have other homologous genes in the genome, and hence can accumulate deleterious mutations because there is another redundant gene in the genome?

And can I check you made the database searching a protein database for homologues (like SwissProt)? 

Thanks,
Pauline

**Comment by Chenglin20170390** [comment]
Hi, Pauline
     Many thanks for your quick response and advice, I will check the genes in superfamilies. The below are the parameters that we made the sift database for 4 haplotype genomes.
```
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=11
MITO_GENETIC_CODE_TABLENAME=Plant Plastid Code

PARENT_DIR=/04_sift/02
ORG=potato
ORG_VERSION=
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=sift4g/bin/sift4g
PROTEIN_DB=opt/databases/uniref90/uniref90.fasta
```

For the deleterious gene, we mark the genes which have at least one deleterious mutation. We wondering whether it‘s a bit too arbitrary. Do you think we should filter the result and make a cutoff ? for example, If there is one deleterious mutation in a gene, we will treat it to no deleterious gene since there may have FN？
    
 We also notice that you mark the deleterious mutation as their `sift score below 0.05`. Is this score similarly to P-value?  can we try 0.03  or 0.01 to reduce FN？

**Comment by pauline-ng** [comment]
Hi Michael,

Your protein database is good.

I just remembered, there is a "SIFT_median_sequence_info" field. If it is too high (close to 4.32), then amino acid will be predicted deleterious. This is because there are not enough diverse sequences.

So could you try rerunning your study with :

`zcat chr/$i/${i}_sift_database/chr${chr}_${hap}.gz |grep 'ref' |awk ' ($11<0.05 && $12 < 3.5) {print}'`

Requiring that the SIFT_median_seq_info is < 3.5 will restrict predictions to where there is enough diverse sequences (and reduce false positives).

**Comment by Chenglin20170390** [comment]
Hi  Pauline,
 After using the command you recommend the result has a slight change, but not too much. The 4 genes with 4 genes have deleterious mutation still in the dominant stage. 
4 genes with no deleterious mutation 9167 ----> 9596
4 genes with only 1 gene have deleterious mutation 1172 -----> 1149
4 genes with only 2 genes have deleterious mutation 1079 ----->1076
4 genes with only 3 genes have deleterious mutation 1565 -----> 1577
4 genes with 4 genes have deleterious mutation 10103 ----->9688

Then, we try to use the vcf method to annotate deleterious mutation, we align each haplotype reads to a reference genome and use that genome to call the vcf file and do statistics. the result is shown below (algene0/1/2/3/4 represent how many genes have the deleterious mutation).
This results look good.
![image](https://user-images.githubusercontent.com/33062118/141489028-2c3e6768-1339-4613-87b7-7506a4ac481c.png)


   Do you have any suggestions about the denovo assemble genome and vcf method to detect deleterious mutation? why they are so different? or does my parameter have the problem?

**Comment by pauline-ng** [comment]
Hi Cheng Lin,

I don't understand what you did when you say "we try to use the vcf method to annotate deleterious mutation, we align each haplotype reads to a reference genome and use that genome to call the vcf file and do statistics. the result is shown below (algene0/1/2/3/4 represent how many genes have the deleterious mutation."

However, the results you showed above look ok right?

Thanks,
Pauline

**Comment by Chenglin20170390** [comment]
Hi， Pauling

Yes,  the results showed good based on vcf method. 

  Vcf method to annotate deleterious mutation I followed the instruction of `https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB#annotate`. 
![image](https://user-images.githubusercontent.com/33062118/141604346-410f81c2-232a-4d68-a768-7b1773aed1f2.png)
    I individually classify sift4g prediction into 2 types but I don't know ok or not; 
1) based on genome assembly method,  we can classfy the deleterious mutation only based on the `sift_database` (name.gz). 
2) base on vcf file as mentioned above. we can classfy the deleterious mutation based on the `sift_database and vcf file.
`

**Comment by pauline-ng** [comment]
Yes, this is OK.
