### ISSUE TITLE
SYNONYMOUS Identified as DELETERIOUS

### ISSUE THREAD

**Issue by cfz1998** [rvaser/sift4g#22]
Hi! I don't know why the SYNONYMOUS Identified as DELETERIOUS. Why? Can you give me some hints？
![image](https://user-images.githubusercontent.com/60096719/147311352-6e2a6d58-7be2-4b6d-97d7-7031a48ea677.png)

**Comment by rvaser** [comment]
@pauline-ng, can you please help @dcf774967 with the question? Thanks!

Best regards,
Robert

**Comment by pauline-ng** [comment]
@dcf774967 

Sorry, github sent this to my spam email.

This happens when the original amino acid in the native protein sequence is predicted to be deleterious.  We see this in ~1% of the amino acids. Pseudogenes will also have a lot of these types of predictions.

**Comment by pauline-ng** [comment]
When the original amino acid is predicted deleterious, this can also indicative of sequencing error.

--Pauline

**Comment by cfz1998** [comment]
> @pauline-ng, can you please help @dcf774967 with the question? Thanks!
> 
> Best regards, Robert
Thank you! Robert
--dcf

**Comment by cfz1998** [comment]
> When the original amino acid is predicted deleterious, this can also indicative of sequencing error.
> 
> --Pauline
Thank you! pauline
--dcf
