### ISSUE TITLE
No result, no error

### ISSUE THREAD

**Issue by yijiao2022** [rvaser/sift4g#23]
Hello,

I am trying to run sift4G with my own database. I have checked the chromosome names of the vcf matched the database. But no result at all. No error, either. Could you please give me any suggestions to fix it?
Below is an example of my VCF file. 
1	103	.	C	T	45.17	PASS	.
1	112	.	C	T	40.13	PASS	.
1	405	.	C	T	209	PASS	.
1	670	.	G	A	77	PASS	.

This is what I got when I ran sift4G

Started Running .......
Running in Multitranscripts mode

Chromosome	WithSIFT4GAnnotations	WithoutSIFT4GAnnotations	Progress
1			0			0			Completed : 1/1

Merging temp files....
SIFT4G Annotation completed !
Output directory:.

**Comment by pauline-ng** [comment]
Hi,

- There should be 10 columns in the VCF file. The SIFT info will be added to the 8th column (the INFO column)
- Does your VCF file have a header?
- Is the VCF file tab-delimited?
- The database files should not start with "chr"

Pauline

**Comment by yijiao2022** [comment]
Thank you for the reminder.
The issue is fixed now after I added the header back to the VCF.

**Comment by wujiang19841114** [comment]
It seems I have a same problem,but a little difference：
The VCF files are divided into two subgroups ,and both has a same sample size. But after annotating the two VCF files,  one result is 

Chromosome      WithSIFT4GAnnotations WithoutSIFT4GAnnotations        Progress
Chr1                    0                       824867                  Completed : 1/1

Merging temp files....
SIFT4G Annotation completed !


the other is 


Chromosome      WithSIFT4GAnnotations   WithoutSIFT4GAnnotations        Progress
Chr1                    1136                    823731                  Completed : 1/1

Merging temp files....
SIFT4G Annotation completed !


I can't figure out why the first subgroup's WithSIFT4G Annotations is 0?
Thank you !

**Comment by pauline-ng** [comment]
Only 0.1% of the 2nd file is annotated (1136/823731), so it looks like most variants in these samples are not in coding regions.

**Comment by mb47** [comment]
> Hi,
> 
>     * There should be 10 columns in the VCF file. The SIFT info will be added to the 8th column (the INFO column)
> 
>     * Does your VCF file have a header?
> 
>     * Is the VCF file tab-delimited?
> 
>     * The database files should not start with "chr"
> 
> 
> Pauline

Hi Pauline,

I am having issues with the chromosome naming - I am building a custom database and my chromosomes are named e.g. "chr1H", "chr2H", etc. -- this applies to all my relevant files (FASTA, VCF, GFF). How can I get around this issue? Is there an option when building the sift database to specify the format of the chromosome names? I couldn't find one. 

thank you!

**Comment by pauline-ng** [comment]
The program should run OK with "chr" in it -- we tested this with human GRCh38 which has "chr'. 

The program cleans out "chr' for the filenames, but when you use the SIFT annotation jar program, it will also ignore "chr". So basically proceed and everything should work out.

**Comment by mb47** [comment]
Hi Pauline,

thanks for the swift reply. As it stands, sift is not producing any annotations, and I am getting the following error message (sorry, I forgot to include this):

The following chromosomes (or scaffolds/contigs) are not found in the SIFT 4G database and will not be annotated:
3H
Please contact us if you have any questions.
/mnt/shared/scratch/mbayer/apps/sift/scripts_to_build_SIFT_db/test_files/Bowman/3H.regions does not exist
3H			0			9418			Completed : 1/1

**Comment by mb47** [comment]
I should add, the corresponding files in the database directory all are named chr3H.gz,  chr3H.regions, chr3H_SIFTDB_stats.txt.

**Comment by pauline-ng** [comment]
try renaming your files:
 chr3H.gz to 3H.gz
 chr3H.regions to 3H.regions
 
and see if that works.

Also, can you paste your contents of chr3H_SIFTDB_stats.txt here so I can see it worked.

**Comment by pauline-ng** [comment]
Closing this issue. a new issue should have been created. Go to

https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/88
