### ISSUE TITLE
the problem annovatation a vcf

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [rvaser/sift4g#24]
![SIFT](https://user-images.githubusercontent.com/101324838/159142020-1d84871b-46f9-4457-8406-3471f3438967.jpg)
hello, I run the sift4g after creating the datebase, but the results show just the chr1 with the ouput. and the the output of chr 1 with all NA
![1647733181(1)](https://user-images.githubusercontent.com/101324838/159142046-2fe10725-96fa-4c3b-8f40-a6e90863ff73.jpg)
 How could i do with this error?
Best wishes

**Comment by pauline-ng** [comment]
1) Please send me list the files for the SIFT database. 
For example,
```
1.gz
1.regions
1_SIFTDB_stat.txt
2.gz
2.regions
2_SIFTDB_stats.txt
```

2)  For the first 1.gz file, please post the first 15 lines.

**Comment by Jiangjiangzhang6** [comment]
![sift_2](https://user-images.githubusercontent.com/101324838/159142971-715e1d31-f11c-48db-99cf-3d46781ebea4.jpg)
![sift_1](https://user-images.githubusercontent.com/101324838/159142972-2397829f-2e4b-44e9-a408-3c7f6eb47dc4.jpg)


Hello, the database created not contain prefix 1. 2. et al, its chr1, chr2 and motified the names to this.
![sift_3](https://user-images.githubusercontent.com/101324838/159143022-5a497ccf-6b41-4122-b116-1ce4a0f6511b.jpg)

**Comment by pauline-ng** [comment]
The files should not start with "chr". Is there a difference between 1.gz and chr1.gz?

SIFT will be looking for 1.gz, 2.gz, etc.  It will not look at chr1.gz, chr2.gz...

(The staff who coded the SIFT 4G annotator dropped the "chr", if you added it back in, it would cause problems.)

**Comment by Jiangjiangzhang6** [comment]
> The files should not start with "chr". Is there a difference between 1.gz and chr1.gz?
> 
> SIFT will be looking for 1.gz, 2.gz, etc. It will not look at chr1.gz, chr2.gz...
> 
> (The staff who coded the SIFT 4G annotator dropped the "chr", if you added it back in, it would cause problems.)

I changged the file just "cp chr1.gz 1.gz",  the software just generated the chr1.gz.  when its chr1.gz, the bug shown the 1.gz not exit, so chang the name, but why the result were NA?

**Comment by pauline-ng** [comment]
Please send me the first 15 lines of the 1.gz file, and some variant lines from your vcf file.

**Comment by Jiangjiangzhang6** [comment]
![sift_1](https://user-images.githubusercontent.com/101324838/159143471-f5e7a8e9-d5a1-455d-8ca3-79b1bd4540c1.jpg)
Hello, this  lines were in 1.gz;


![SIFT_2](https://user-images.githubusercontent.com/101324838/159143475-8288a041-b4b9-44aa-9c68-a6f602e00dc9.jpg)
this was the vcf lines

**Comment by Jiangjiangzhang6** [comment]
> ![sift_1](https://user-images.githubusercontent.com/101324838/159143471-f5e7a8e9-d5a1-455d-8ca3-79b1bd4540c1.jpg) Hello, this lines were in 1.gz;
> 
> ![SIFT_2](https://user-images.githubusercontent.com/101324838/159143475-8288a041-b4b9-44aa-9c68-a6f602e00dc9.jpg) this was the vcf lines

I analyzed the plant genome, with not dbSNP

**Comment by pauline-ng** [comment]
I think I need to have your original files to debug this. Can you upload it on a public server, send me a dropbox link, or something like that?

**Comment by pauline-ng** [comment]
Just the chr1 files (1.* ) and partial vcf would be fine.

**Comment by Jiangjiangzhang6** [comment]
> I think I need to have your original files to debug this. Can you upload it on a public server, send me a dropbox link, or something like that?

OK. I would unpload the files just 2000 lines ,the original vcf with 182GB, 

> Just the chr1 files (1.* ) and partial vcf would be fine.

ok, I extracted it and upload

**Comment by Jiangjiangzhang6** [comment]
[1.regions.zip](https://github.com/rvaser/sift4g/files/8310452/1.regions.zip)
[1.txt.gz](https://github.com/rvaser/sift4g/files/8310453/1.txt.gz)
[1_SIFTDB_stats.txt](https://github.com/rvaser/sift4g/files/8310454/1_SIFTDB_stats.txt)

**Comment by Jiangjiangzhang6** [comment]
> [1.regions.zip](https://github.com/rvaser/sift4g/files/8310452/1.regions.zip) [1.txt.gz](https://github.com/rvaser/sift4g/files/8310453/1.txt.gz) [1_SIFTDB_stats.txt](https://github.com/rvaser/sift4g/files/8310454/1_SIFTDB_stats.txt)



> Just the chr1 files (1.* ) and partial vcf would be fine.

would  I extracted the  front 2000 lines in 1.gz,its ok ?

**Comment by Jiangjiangzhang6** [comment]
> [1.regions.zip](https://github.com/rvaser/sift4g/files/8310452/1.regions.zip) [1.txt.gz](https://github.com/rvaser/sift4g/files/8310453/1.txt.gz) [1_SIFTDB_stats.txt](https://github.com/rvaser/sift4g/files/8310454/1_SIFTDB_stats.txt)

[1.gz](https://github.com/rvaser/sift4g/files/8310458/1.gz)
the 1.txt was the vcf to annotation

**Comment by pauline-ng** [comment]
So when I put in a coding variant (I just took a position in the 1.gz file), it works for me.
[1_coding.vcf.gz](https://github.com/rvaser/sift4g/files/8310552/1_coding.vcf.gz)

Can you try the attached file and see if you can get a SIFT annotations?

**Comment by pauline-ng** [comment]
Also, please confirm there is no 1-off for genomic position. The ref allele in the VCF must match the genomic sequence used to build the database, otherwise no annotation will be printed.

**Comment by Jiangjiangzhang6** [comment]
its strange

> 
I try it but wit not output?


> Also, please confirm there is no 1-off for genomic position. The ref allele in the VCF must match the genomic sequence used to build the database, otherwise no annotation will be printed.

yeah, the` reference with soft-mas, but i saw the the database, it was like well

**Comment by Jiangjiangzhang6** [comment]
java  -Xmx300G -jar ../SIFT4G_Annotator.jar -c -i /public/home/zmsong/jjzhang/snp/index/treemix/sift4g/garlic_result/1.txt -d /public/home/zmsong/jjzhang/snp/index/treemix/sift4g/SIFT4G_Create_Genomic_DB-master/test_files/garlic/ga.V1 1.txt

> So when I put in a coding variant (I just took a position in the 1.gz file), it works for me. [1_coding.vcf.gz](https://github.com/rvaser/sift4g/files/8310552/1_coding.vcf.gz)
> 
> Can you try the attached file and see if you can get a SIFT annotations?

this was the command for annotation the vcf

**Comment by pauline-ng** [comment]
I get results with:

`java -jar SIFT4G_Annotator.jar -c -i 1_coding.vcf -d <path_to_database> -r <output> -t`

**Comment by pauline-ng** [comment]
Your command doesn't pass in the VCF file? Your -i file has a suffix of .txt. It needs to be a VCF file.

**Comment by Jiangjiangzhang6** [comment]
> Your command doesn't pass in the VCF file? Your -i file has a suffix of .txt. It needs to be a VCF file.

thank you, use` your vcf and command had the result,  I would run it, thank you for your help

**Comment by Jiangjiangzhang6** [comment]
> Your command doesn't pass in the VCF file? Your -i file has a suffix of .txt. It needs to be a VCF file.

maybe caused by the soft-mask the genome ?  the vcf with all upper, and the database created by the sof-mask genome ,need to creadted again?
