### ISSUE TITLE
About the number of DELETERIOUS from SIFT annotation

### ISSUE THREAD

**Issue by mm-98** [rvaser/sift4g#25]
Hello Robert,
I used the genome fasta file , protein fasta files and genome annotation file to build the databas.Despite some warning, the database was set up successfully.SIFT numeric scores  columns 10-12  have many rows say "NA".CHECK_GENES.LOG file columns 2-4 value very low.Through SIFT predicted ,I fonded that 85675 missense mutations in 42554 genes ,only 15777 sites was  identified as NONSYNONYMOUS , 4141 sites was identified as DELETERIOUS and  1160 sites was  identified as TOLERATED .  I don't know the reason why many missense mutation sites can't be dentified.

And here is my file and  command lines:
gene-annotation-src:
D.gtf.gz 6.27MB
D.pep.all.fa.gz 10.0MB
less -S D.gtf.gz

>pseudo-chr0     EVM     transcript      61149   61566   .       -       .       transcript_id "D15542.t1"; gene_id "D15542"
>pseudo-chr0     EVM     exon    61149   61417   .       -       .       transcript_id "D15542.t1"; gene_id "D15542";
>pseudo-chr0     EVM     exon    61485   61566   .       -       .       transcript_id "D15542.t1"; gene_id "D15542";
>pseudo-chr0     EVM     CDS     61149   61417   .       -       2       transcript_id "D15542.t1"; gene_id "D15542";
>pseudo-chr0     EVM     CDS     61485   61566   .       -       0       transcript_id "D15542.t1"; gene_id "D15542";

less -S D.pep.all.fa.gz

>protein|D19569.t1 ID=D19569.t1|Parent=D19569|Name=
MSGPGYMDHVFKANANSNSNPPCESKKMDPATKIGATSTTNTCPLPSPKIFANSELLTTSTEAAVTIPVNTKTSDAKSCQSVTNYGRVTGNSTRSDSLESSSAPLKPHTGGDVRWDAINSVCSKDSPLGLSHFRLLKRLGYGDIGSVYLVELRGTNTYFAMKVMDRGS
>protein|D19568.t1 ID=D19568.t1|Parent=D19568|Name=
MLLQNWSFSGGLLSHSLLLHSRNPSNIISSALFPRRKAKAATTFLCLRLGIDEIAEIAHNKVLIAAVVSAAIGQLSKPFTSAILYGNKNNFDFRAAFQAGGFPSTHSSAVVATATSLGLERGFSDTIFGLAVVYAGLIMYDAQGVRREVGTHAKALNSVLLKNQLNSI
>protein|D19566.t1 ID=D19566.t1|Parent=D19566|Name=
MVSPLLLQIPINTTSNGVTSAKANTNYPLPSPPVTSQSRELEEAEVEADDEVVGNGVLNQNVLSEDEYIRIFPRGIGPKPTEFKCEASRETPVVIMNHINLVEILMDLVEILMDVGSK*

chr-src:
reference.fa.gz 305MB
less -S reference.fa.gz

>pseudo-chr0
TGGACTGACTGGACTGGGAAAATTTGTATTGTATTGGAGTATTGGATTGTTCTGGGAGTATTGACTTGTATTGTACATGTAAAGTATGAAAAGCTTGTAAAAGGACAAAACCTGGTCCCACATGGGGTGAAGTTTAAGTCGTCCTTTGAAAGATAGGATAGTCCTTAT.....
......
.....
.....
>pseudo-chr9
TTATATATTAATATATAATAATAAATAATGAGAAATAAAATACCAAAAATACTATAATTACCTAGAACACCTAAAAATACCTAAACTTAATCAAAACTTATTTTTATGGATTTTTAAGGATTTTCTAAAGAGTAAAAACTAATTAACACTAAAAATACCAAAAAAATA....
....
>scaffold808_size847463_ERROPOS700000
ATGATCTTCCAAAACTTGGAAAACCATCTTCAAGTGTTTGTGGACCATGTCAGCTAGGAAAGCAAATTAAGAGTCCTCACAAGAAGTCAAAATTCATTCACACCTCTCGTGTCTTAGAGTTGATTAATATGGATCTCATGGGTCCAATGAGAACAGAAAGCGTAGGGG.....
.....

Configuration File :
D.txt 

>GENETIC_CODE_TABLE=1
>GENETIC_CODE_TABLENAME=Standard
>MITO_GENETIC_CODE_TABLE=11
>MITO_GENETIC_CODE_TABLENAME=Bacterial, Archaeal and Plant Plastid
>
>PARENT_DIR=/loc/d01/user009/D/third_build_sift
>ORG=D
>ORG_VERSION=D_v1
>DBSNP_VCF_FILE=

>#Running SIFT 4G
>SIFT4G_PATH=/loc/d01/user009/software/sift4g/bin/sift4g
>PROTEIN_DB=/loc/d01/user009/D/uniref90.fasta
>COMPUTER=GIS-KATNISS

>#Sub-directories, don't need to change
>GENE_DOWNLOAD_DEST=gene-annotation-src
>CHR_DOWNLOAD_DEST=chr-src
>LOGFILE=Log.txt
>ZLOGFILE=Log2.txt
>FASTA_DIR=fasta
>SUBST_DIR=subst
>ALIGN_DIR=SIFT_alignments
>SIFT_SCORE_DIR=SIFT_predictions
>SINGLE_REC_BY_CHR_DIR=singleRecords
>SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
VDBSNP_DIR=dbSNP

>#Doesn't need to change
>FASTA_LOG=fasta.log
>INVALID_LOG=invalid.log
>PEPTIDE_LOG=peptide.log
>ENS_PATTERN=ENS
>SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

perl make-SIFT-db-all.pl -config D.txt

sift4g -t 48 -d ./uniref90.fasta -q /loc/d01/user009/D/third_build_sift/all_prot.fasta --subst /loc/d01/user009/D/third_build_sift/su
bst --out/loc/d01/user009/D/third_build_sift/SIFT_predictions --sub-results

Use of uninitialized value $fasta_subseq in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line 446, <IN_TX> line 20913.
Argument "" isn't numeric in numeric eq (==) at generate-fasta-subst-files-BIOPERL.pl line 465, <IN_TX> line 21729.
Use of uninitialized value $mutated_aa in string eq at generate-fasta-subst-files-BIOPERL.pl line 894.
Use of uninitialized value $aa2 in string eq at generate-fasta-subst-files-BIOPERL.pl line 621.
Argument "" isn't numeric in addition (+) at generate-fasta-subst-files-BIOPERL.pl line 866.
Use of uninitialized value $coord in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line 918.
Use of uninitialized value $exon_num in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line 918.
....

* skipping protein [ D29247.t1 ]: substitution list has a position out of bounds (line: D252E, query length = 251) * 
* ....
* skipping protein [ D44925.t1 ]: substitution list has a position out of bounds (line: I525I, query length = 524) *
* skipping protein [ D44931.t1 ]: substitution list has a position out of bounds (line: Q67Q, query length = 66) *
* processing queries: 100.00/100.00% *
** Aligning queries with candidate sequences **
* processing database part 64 (size ~1.00 GB): 100.00/100.00% *

** Selecting alignments with median threshold: 2.75 **
* processing queries: 100.00/100.00% *

** Generating SIFT predictions with sequence identity: 100.00% **
* processing queries: 100.00/100.00% *
 .....
 All done!

CHECK_GENES.LOG file:
Chr	Genes with SIFT Scores	Pos with SIFT scores	Pos with Confident Scores
>pseudo-chr0	10 (227/2287)	14 (637725/4718761)	2(11664/637725)
>pseudo-chr1	26 (1338/5214)	35 (4911882/13886195)	12(595766/4911882)
>pseudo-chr10	24 (664/2724)	34 (2309132/6785718)	17(384198/2309132)
>pseudo-chr11	24 (576/2441)	32 (1872042/5869154)	14(266614/1872042)
.....

My directory:

>4.0K    ./SIFT_alignments
>3.8G    ./SIFT_predictions
>1.2G    ./subst
>83G     ./singleRecords
>220K    ./singleRecords_with_scores
>306M    ./chr-src
>4.0K    ./dbSNP
>37M     ./gene-annotation-src
>220M    ./fasta
>2.3G    ./D_v1
>4.0K    ./tmp
>91G     .

I would be thankful for all the help.
Best regards,
Enter

**Comment by pauline-ng** [comment]
Hi Enter,

Your #'s are on the low side. It sounds like not all of the proteins had homologous alignments. Is this an unusual organism?

Also, as  sanity check, when you inspect the file at:

`/loc/d01/user009/D/third_build_sift/all_prot.fasta`

does it look like all of the proteins in the genome are represented correctly?

Thanks,
Pauline

**Comment by mm-98** [comment]
Hi, Pauline,
It's a relict plant. All_prot.fasta  file tree of my data looks like this:
>118973,119165
AFVTGCKTFWLLHINVFLNHVIKESSFKIHLPYLIVIVCSYSEHNPDGFAHSYWRKGFFIVNSLSLFITFSHAPCFVGLYLSILAYLPFVDPFAANKYYTLALVYQSSDLIGVHRIHLAFHGFMPFSANRCLTSPPCNALDHSFHHCLHNERVPHHLDRDTHISAVVR....
>119139,119339,120895,121335,140334,146591,147063,147279,154943,156351,162839,166293,167353
ACXXETQPHSNRMPFFFMPVCMIALTLLKGMXXLRALSYSLSTELLEKPDGSLGTGFAFLIAPVLQARFCHYSSDTEGLVCCTIGRASADCSPAFTLLAIALVYSPPRGFTTEHVTVLGPRCFSLSIWEVADDPIGRGVQSLVIHSRRVDTISGASFPPQLSEGVAQL....
>.....
>D00016.t2
MVEQIPLLRQMMITRALGQRSNVHVRIQQRNGRKSLTTVQWGKAAKEYFHVMSIVTREIPTWVSSCCSSRVQQLWEEIPWRETSILADVKSMKDLYPSFD
>D00025.t1
MVDDGDMGGDGGGYEVWKSDDKVAGLAAEMEESWWFLVSWDGVSRELQEAMAGEFGAGGGTGWRRAVAVGFGDGVVVVSGRRRMLR
>D00026.t1
MADCLMVVLRQKLRALRLRWRNHGGFLCRGMVFQEVLMERGKLQEAMAGEFGAGGGAGWRRAVAVGFGDEVVVVSGRRRMLR

Best regards,
Enter

**Comment by sandyplus** [comment]
Hi, @mm-98 
Did you solve your problem?
I met the same problem.
The program seems to predict only 1/3 of my proteins.
I got a lot of 'NA NA' in my final results.

Best regards,
Sandy

**Comment by pauline-ng** [comment]
@sandyplus 
Please check this[ thread](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/57) for some tips to QC your data. For that case, the user found that his gene annotations were low-quality by BUSCO

**Comment by sandyplus** [comment]
Hi, @mm-98 
I finally figure out the problem. I guess it comes from a bug of **make-single-records-BIOPERL.pl**.
Please check [this thread](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/57).

Best regards,
Sandy
