### ISSUE TITLE
processing database part 975 than finish，and nothing generate

### ISSUE THREAD

**Issue by wpf95** [rvaser/sift4g#26]
Hi，rvaser，
Thank you for create a great software,i would like to use it to annotate animal genome. I use conda to install sift4g,when i run the sift4g in test_file,it can not generate anything, i do not know why . Following is issue i meet
![image](https://user-images.githubusercontent.com/85783400/171318233-ef75debc-97cc-432a-b714-06f53a63e5e2.png)

I also want to do a datebase for my species，then run the make-SIFT-db-all.pl
But it always processing database part 975，can not go next，so what happened ？i want know，it is a big problem that i can not resolve.

converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
/home/Wangpengfei/anaconda3/envs/sift4g/bin/sift4g -d /home/Wangpengfei/sift4g/SIFT4G_Create_Genomic_DB-master/nr -q /home/Wangpengfei/sift4g/SIFT4G_Create_Genomic_DB-master/test_files/bovine_ncbi/all_prot.fasta --subst /home/Wangpengfei/sift4g/SIFT4G_Create_Genomic_DB-master/test_files/bovine_ncbi/subst --out /home/Wangpengfei/sift4g/SIFT4G_Create_Genomic_DB
** Checking query data and substitutions files **

processing queries: 0.00/100.00% ^M processing queries: 0.01/100.00% ^M processing queries: 0.01/100.00% ^M processing queries: 0.01/100.00% ^M processing queries: 0.01/100.00% ^M processing queries: 0.02/100.00% ^M processing queries: 0.02/100.00% ^M processing queries: 0.02/100.00% ^M processing queries: 0.02/100.00% ^M processing querie..............................................................................** Searching database for candidate sequences **
processing database part 1 (size ~0.25 GB): 0.00/100.00% ^M processing database part 1 (size ~0.25 GB): 2.50/100.00%processing database part 975 (size ~0.25 GB): 92.50/100.00% ^M processing database part 975 (size ~0.25 GB): 95.00/100.00% ^M processing database part 975 (size ~0.25 GB): 97.50/100.00% ^M processing database part 975 (size ~0.25 GB): 100.00/100.00%

**Comment by Afei99357** [comment]
I have the similar issue. finishing processing queries: 0.00/100.00% ^M processing queries: 0.01/100.00% ^M processing queries: 0.01/100.00% ^M, then nothing continues.

Can i ask how the issue be solved?

**Comment by SeanTater** [comment]
I found out it is the memory issue for me for this situation, it use a lot of memory and the app does not tell you that. mine needs at least 35 GB memory

**Comment by taolincj** [comment]
I also encountered the same problem! I have set up enough memory, but it does not work with the following error:
`** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 2 (size ~0.25 GB): 100.00/100.00% *

Illegal instruction (core dumped)`

Any suggestions?
