### ISSUE TITLE
access problem for gene-annotation-src

### ISSUE THREAD

**Issue by PrincyJohnson** [rvaser/sift4g#27]
Hello,

I am trying to create sift database for peas. I have my files downloaded. I am getting an error that says it cannot access my gene-annotation-src

Error:
entered mkdir ./newpeas
/Pisum_sativum_v1awpeas
converting gene format to use-able input
ls: cannot access '/gene-annotation-src': No such file or directory
Unable to open  for reading
done converting gene format
/*.gz: No such file or directory
DNA files do not exist or did not unzip properly

Config file:

GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=1
MITO_GENETIC_CODE_TABLENAME=Plant Plastid Code

PARENT_DIR=./newpeas/peas
ORG=Pisum_sativum
ORG_VERSION=Pisum_sativum_v1a
DBSNP_VCF_FILE=SNPD4.vcf.gz

#Running SIFT 4G
SIFT4G_PATH=./sift4g/bin/sift4g
PROTEIN_DB=./scripts_to_build_SIFT_db/test_files/fastafiles/uniprot-pisum.fasta

# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

**Comment by pauline-ng** [comment]
Hi,

Please set full paths, not relative paths in the config file. 
`
PARENT_DIR=./newpeas/peas`

won't work, it should be something like

`PARENT_DIR=/home/princyjohnson/newpeas/peas`

**Comment by pauline-ng** [comment]
Closed because this question refers to code in another repository.

Please reopen in the [SIFT4G_Create_Genomic_DB](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB) repo as a **new** issue if still unresolved. Problems are referring to SIFT4G_Create_Genomic_DB code.

**Comment by pauline-ng** [comment]
Closed -- this question is referring to code in another repository.
