### ISSUE TITLE
SIFT4G_Create_Genomic_DB

### ISSUE THREAD

**Issue by PrincyJohnson** [rvaser/sift4g#28]
Hello,

I tried using the full path in the  parent_dir but still it shows that it can't access the gene-annotation-src file. Can you please help me?

I have attached my config file,

Thanks,
Princy
[peas_config.txt](https://github.com/rvaser/sift4g/files/9021802/peas_config.txt)

**Comment by pauline-ng** [comment]
Did the test files work for you?

Also, I noticed your PROTEIN_DB isn't a full path.

**Comment by pauline-ng** [comment]
Ugh, wrong repo again. Princy, please open this issue at this repo:  [SIFT4G_Create_Genomic_DB](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB)  

Problems (and solutions) are referring to SIFT4G_Create_Genomic_DB code

**Comment by pauline-ng** [comment]
Closed because this question is referring to code in another repository.
