### ISSUE TITLE
#Chr17_scores.Srecords': No such file or directory

### ISSUE THREAD

**Issue by XIAO2Mark** [rvaser/sift4g#29]
Hi,

I have tried to use the SIFT4G to build my own SIFT database for many times, but it still was unsuccessful. can you help me to check it?  The details as bellow: 

** Searching database for candidate sequences **
* processing database part 1 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
* processing database part 1 (size ~1.00 GB): 100.00/100.00% *

** Selecting alignments with median threshold: 2.75 **
* processing queries: 100.00/100.00% *

** Generating SIFT predictions with sequence identity: 100.00% **
* processing queries: 100.00/100.00% *

done getting all the scores
populating databases
cat: /home/scripts_to_build_SIFT_db/test_files/singleRecords/Chr1.singleRecords: No such file or directory
can't open /home/scripts_to_build_SIFT_db/test_files/singleRecords/Chr1.singleRecords at map-scores-back-to-records.pl line 122.
Unable to read from /home/scripts_to_build_SIFT_db/test_files/singleRecords_with_scores/Chr1_scores.Srecords
cat: /home/scripts_to_build_SIFT_db/test_files/singleRecords/Chr1.singleRecords_noncoding.with_dbSNPid: No such file or directory
Traceback (most recent call last):
  File "make_regions_file.py", line 68, in <module>
    get_regions (chrom_file, out_file)
  File "make_regions_file.py", line 31, in get_regions
    pos = get_pos (first_line)
  File "make_regions_file.py", line 8, in get_pos
    return int (fields[0])
ValueError: invalid literal for int() with base 10: ''
rm: cannot remove '/home/scripts_to_build_SIFT_db/test_files/singleRecords_with_scores/Chr1_scores.Srecords': No such file or directory

many thx.

**Comment by pauline-ng** [comment]
Closed because also reported in SIFT4G repo issue [#69](https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/69)
