### ISSUE TITLE
Not able to generate SIFT databse 

### ISSUE THREAD

**Issue by nilesh-tawari** [rvaser/sift4g#3]
[all_prot.zip](https://github.com/rvaser/sift4g/files/1473390/all_prot.zip)
[subst.tar.gz](https://mega.nz/#!64YCXJDL!4jc0_OgF6tOQYucgv418vSvT91-q9BSTNLDi5f8BRE4)

Dear Robert,
I am unable to create SIFT4G database. Below is my SIFT4G command and screen output,

sift123@sift123-Precision-T5600:/mnt1/scripts_to_build_SIFT_db$ /mnt1/SIFT4G_2.0.0/bin/sift4g -d /mnt1/protein_db/uniprot90_Jul2016/uniref90.fasta -q /mnt1/SIFT_databases//goat/all_prot.fasta --subst /mnt1/SIFT_databases//goat/subst --out /mnt1/SIFT_databases//goat/SIFT_predictions --sub-results
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *
 
** Searching database for candidate sequences **
Killedessing database part 1 (size ~0.25 GB): 97.50/100.00% *

The all_prot.fasta and subst.tar.gz files are attached for debugging purpose. Please let me know if you need any additional information. 

Thank you,
-Nilesh

**Comment by rvaser** [comment]
Hi Nilesh,
how much RAM do you have on your machine? I ran your proteins on the uniref90 database and peak memory consumption is around 30GB on 8 threads (might be higher on more threads).

Best regards,
Robert

**Comment by nilesh-tawari** [comment]
Hi Robert,
If memory is the issue, then will splitting all_prot.fasta file and running SIFT4G is a way to finish the job?
Or are there any other ways I can finish this job?
Thanks,
-Nilesh

**Comment by rvaser** [comment]
Yes, you can split your proteins in several smaller files in order to reduce memory consumption. Another option is to use fewer threads.

Best regards,
Robert

**Comment by nilesh-tawari** [comment]
Hi Robert,
Splitting files helped, SIFT is now running fine. 
Thank you,
-Nilesh
