### ISSUE TITLE
Errors in creating SIFT Database for rheMac10

### ISSUE THREAD

**Issue by npb596** [rvaser/sift4g#30]
Hello,

I am continuing an issue here that began with this thread: https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/70

The current issue is that I run into a segmentation fault when running the sift4g command to generate SIFT_predictions. 

This is the most recent output I get:

** Aligning queries with candidate sequences **

    processing database part 1 (size ~1.00 GB): 0.00/100.00% *
    processing database part 1 (size ~1.00 GB): 2.50/100.00% *
    processing database part 1 (size ~1.00 GB): 5.00/100.00% *
    processing database part 1 (size ~1.00 GB): 7.50/100.00% *
    processing database part 1 (size ~1.00 GB): 10.00/100.00% *
    processing database part 1 (size ~1.00 GB): 12.50/100.00% *
    /cm/local/apps/slurm/var/spool/job391367/slurm_script: line 16: 18084 Segmentation fault sift4g -t 20 -q /home/npb0015/reinforcement_project/all_prot.fasta -d /home/npb0015/reinforcement_project/Reference_files/uniprot_sprot.fasta --subst /home/npb0015/reinforcement_project/subst --out /home/npb0015/reinforcement_project/SIFT_predictions/ --sub-results

This error comes from running the sift4g command given in the error, which is essentially the same as that suggested on October 16th in the original thread (I get the same error running that command exactly as is). Since a segmentation fault usually means an inability to access the memory required I've tried runs as high as 248GB RAM but still receive the same error, so I assume that is not the issue.

Here I will also provide a link to dropbox for the all_prot.fasta file that has been generated by earlier steps in the database creation.

https://www.dropbox.com/s/ggfgs7senvh3vaf/all_prot.fasta?dl=0

**Comment by pauline-ng** [comment]
Hi Nick,

I looked at your all_prot.fasta file and there are proteins with runs of X's in them. Can you remove these proteins and then try re-running sift4g.

**Comment by npb596** [comment]
I removed those proteins, ran sift4g with the resulting FASTA file and there are SIFT prediction files now, thank you. When running the next step:

perl make-SIFT-db-all-downstream-sift4g.pl -config rheMac10.config.txt

I receive the following errors:

Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr11_NW_021160268v1_random.singleRecords_noncoding
Traceback (most recent call last):
  File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 68, in <module>
    get_regions (chrom_file, out_file)
  File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 31, in get_regions
    pos = get_pos (first_line)
  File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 8, in get_pos
    return int (fields[0])
ValueError: invalid literal for int() with base 10: ''
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr13_NW_021160278v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr13_NW_021160282v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr18_NW_021160356v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr19_NW_021160375v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr4_NW_021160155v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr6_NW_021160190v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chr8_NW_021160222v1_random.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021160452v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021160484v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161041v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161561v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161848v1.singleRecords_noncoding
Traceback (most recent call last):
  File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 68, in <module>
    get_regions (chrom_file, out_file)
  File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 31, in get_regions
    pos = get_pos (first_line)
  File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 8, in get_pos
    return int (fields[0])
ValueError: invalid literal for int() with base 10: ''
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161853v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021161876v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021162246v1.singleRecords_noncoding
Unable to read from /home/npb0015/reinforcement_project/singleRecords/chrUn_NW_021162265v1.singleRecords_noncoding
checking the databases
zipping up /home/npb0015/reinforcement_project/Reference_files/*
gzip: /home/npb0015/reinforcement_project/Reference_files/directory.index.gz already has .gz suffix -- unchanged
gzip: /home/npb0015/reinforcement_project/Reference_files/noncoding.txt.gz already has .gz suffix -- unchanged
gzip: /home/npb0015/reinforcement_project/Reference_files/protein_coding_genes.txt.gz already has .gz suffix -- unchanged
gzip: /home/npb0015/reinforcement_project/Reference_files/rheMac10.ensGene.gtf.gz already has .gz suffix -- unchanged
All done!

These appear to be the same errors that I posted here https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/70 on October 20th, when I still wasn't generating SIFT predictions properly, so not sure why the errors still appear. I am running it with python version 3.9.2. I've looked at the python script a bit and I have some suspicion the ValueError results from a missing or empty chr.gz file but I can't figure what chr would be missing as I know there are chr.gz and regions files.

**Comment by pauline-ng** [comment]
What is your output if you type `python` on the commandline?

What happens if you type 
`python make_regions_file.py`

**Comment by npb596** [comment]
If I type ``python`` on the command line and enter a python terminal is brought up with the following message:
Python 3.9.2 (default, May 10 2022, 20:10:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.

When I enter ``python make_regions_file.py`` I receive the following:
check_SIFTDB.py <sorted file> <outfile>
Traceback (most recent call last):
  File "/mmfs1/home/npb0015/reinforcement_project/SIFT/scripts_to_build_SIFT_db/make_regions_file.py", line 64, in <module>
    chrom_file = sys.argv[1]
IndexError: list index out of range

**Comment by pauline-ng** [comment]
Transferring issue to https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/70
