### ISSUE TITLE
Use of uninitialized value in string ne at check_genes.pl-populating databases

### ISSUE THREAD

**Issue by eggxo** [rvaser/sift4g#31]
Dear rvaser；
I just tried to run the test_file[homo_sapiens_small] for building SIFT_db. Everthing was right until the populating databases state.  There were warnings as：
Use of uninitialized value $siftscore in numeric ge (>=) at check_genes.pl line 53, <DB_IN> chunk 601612175.
Use of uninitialized value $siftscore in string ne at check_genes.pl line 53, <DB_IN> chunk 601612175.
Use of uninitialized value in string ne at check_genes.pl line 56, <DB_IN> chunk 601612175.
Use of uninitialized value in string ne at check_genes.pl line 56, <DB_IN> chunk 601612175
And there were .SIFTpredictions/.aligned.fasta in SIFT_predictions, 21.gz/MT.gz in GRCh38.83. 
Do these warnings influence the results?(The warning message is full of screen and "all done" does not appear.)
When I stopped this command, it showed 
 File "check_SIFTDB.py", line 301, in <module>
    process_chr_file (infile, DNA_base_change_syn_nonsyn_counts, DNA_base_change_aa_pred, all_nonsyn_changes, dbSNP_predictions, novel_predictions, ref_predictions, aa_change_pred) 
  File "check_SIFTDB.py", line 202, in process_chr_file
    for line in siftdb_fp.readlines():
  File "/usr/lib/python3.8/codecs.py", line 319, in decode
    def decode(self, input, final=False):
KeyboardInterrupt

I installed sift4g and SIFT4G_Create_Genomic_DB on ubuntu 20.04 with following packages:
Perl         -- 5.30.0
DBI          -- 1.643
BioPerl      -- 1.7.8
LWP          -- 6.67
Switch       -- 2.17
Python 3.8.10

Best regards.

**Comment by pauline-ng** [comment]
Should be fine. 
Please don't stop the command, you won't get a database.
