### ISSUE TITLE
Problem creating genomic database for new organism

### ISSUE THREAD

**Issue by aamirwkhan06** [rvaser/sift4g#4]
Dear SIFT 4G team

I followed the instructions from "https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB" to construct the database for a new organism. In my case, I am constructing the database for Cicer arietinum. I am getting the following error while running the script "make-SIFT-db-all.pl" using the following command:

Command:
perl make-SIFT-db-all.pl -config test_files/cicer_arietinum_config.txt

Log:
perl make-SIFT-db-all.pl -config test_files/cicer_arietinum_config.txt
converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
cat: ./test_files/cicer_arietinum_genome/fasta/*.fasta: No such file or directory
/data/ngs/Programs_latest/SIFT4G_v2.0.0/bin/sift4g -d ./test_files/protein_db/uniref90.fasta -q ./test_files/cicer_arietinum_genome/all_prot.fasta --subst ./test_files/cicer_arietinum_genome/subst --out ./test_files/cicer_arietinum_genome/SIFT_predictions --sub-results
** Checking query data and substitutions files **

** EXITING! No valid queries to process. **

I also tried running the same script for the test human dataset provided with the package, but I am observing a different error:

Command:
perl make-SIFT-db-all.pl -config test_files/homo_sapiens-test.txt

Log:
converting gene format to use-able input
done converting gene format
making single records file
done making single records template
making noncoding records file
done making noncoding records
make the fasta sequences
done making the fasta sequences
start siftsharp, getting the alignments
/data/ngs/Programs_latest/SIFT4G_v2.0.0/bin/sift4g -d ./test_files/protein_db/uniref90.fasta -q ./test_files/homo_sapiens_small/all_prot.fasta --subst ./test_files/homo_sapiens_small/subst --out ./test_files/homo_sapiens_small/SIFT_predictions --sub-results
** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
what(): regex_error

My config file for the Cicer arietinum looks like:
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=2
MITO_GENETIC_CODE_TABLENAME=Vertebrate Mitochondrial

PARENT_DIR=./test_files/cicer_arietinum_genome
ORG=cicer_arietinum
ORG_VERSION=v1.0
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=/data/ngs/Programs_latest/SIFT4G_v2.0.0/bin/sift4g
PROTEIN_DB=./test_files/protein_db/uniref90.fasta
COMPUTER=mrna

GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

I also pulled the latest sift-4g code and recompiled and run the above mentioned perl script to observe the same set of errors.

I need help to resolve this error and construction of the database for my organism.

It would be really appreciable if I can be guided to resolve the error mentioned.

I would be thankful for all the help.

Best regards
Aamir

**Comment by rvaser** [comment]
Hello Aamir,
the second error indicates that you are probably using the wrong compiler version (minimum required is g++ 4.9). Please verify that by running `g++ --version`. If so, update the compiler, recompile sift4g and run the human example again.
I am not sure about the first error as I am not that familiar with sift database building, but it seems to me that your directory tree is different to that of the human example (from the error the `cat` command can't find its targets). Nonetheless, I will look deeper into it soon.

Best regards,
Robert

**Comment by rvaser** [comment]
I don't see what else could cause the error, please run `tree cicer_arietinum_genome` and paste the result here.

Best regards,
Robert

**Comment by aamirwkhan06** [comment]
Dear Robert

Thanks a lot for your prompt reply. I checked for the g++ version and it shows 4.8.5. I am working on Ubuntu 14.04 server edition and will request system administrator to update the gcc version.

The directory structure for cicer_arietinum_genome is as follows:

cicer_arietinum_genome
|-- all_prot.fasta
|-- chr-src
|   |-- Cicer_arietinum_GA_v1.0.masked.fa
|   `-- directory.index
|-- Cicer_arietinum_GA_v1.0.gene.gtf.gz
|-- dbSNP
|-- fasta
|-- fasta.log
|-- gene-annotation-src
|   |-- Cicer_arietinum_GA_v1.0.gene.gtf.gz
|   |-- Cicer_arietinum_GA_v1.0.gene.pep.fa.gz
|   |-- noncoding.txt
|   `-- protein_coding_genes.txt
|-- invalid.log
|-- Log2.txt
|-- peptide.log
|-- SIFT_alignments
|-- SIFT_predictions
|-- singleRecords
|-- singleRecords_with_scores
|-- subst
`-- v1.0

Please suggest

Thank you

Best regards
Aamir

**Comment by rvaser** [comment]
Could you please send me all of the `*.log` files created? The directory tree looks fine to me, although no proteins and substitution files were created.

Best regards,
Robert

**Comment by aamirwkhan06** [comment]
Dear Robert

"invalid.log" , "peptide.log" and "Log2.txt" are empty files. I have attached "fasta.log" here for your kind reference.

Please suggest

Thank you

Best regards
Aamir

[fasta.log](https://github.com/rvaser/sift4g/files/1495821/fasta.log)

**Comment by rvaser** [comment]
Can you check the sizes of all files generated when you ran `make-SIFT-db-all.pl`? Maybe the annotation files are empty as well (`noncoding.txt` and `protein_coding_genes.txt`)?

Best regards,
Robert

**Comment by aamirwkhan06** [comment]
Dear Robert

Please find the sizes of the files in respective directories as follows:

-rw-rw-r-- 1 aamir ngs    0 Sep 26 11:00 all_prot.fasta
-rw-rw-r-- 1 aamir ngs 1.3M Sep 26 10:20 Cicer_arietinum_GA_v1.0.gene.gtf.gz
-rw-rw-r-- 1 aamir ngs   68 Nov 22 08:46 fasta.log
-rw-rw-r-- 1 aamir ngs    0 Nov 22 08:46 invalid.log
-rw-rw-r-- 1 aamir ngs    0 Nov 22 08:46 Log2.txt
-rw-rw-r-- 1 aamir ngs    0 Nov 22 08:46 peptide.log

chr-src:
total 515M
-rwxrwx--- 1 aamir ngs 513M Sep 25 14:49 Cicer_arietinum_GA_v1.0.masked.fa
-rw-r--r-- 1 aamir ngs 352K Nov 22 08:46 directory.index

dbSNP:
total 0

fasta:
total 0

gene-annotation-src:
total 8.7M
-rw-rw-r-- 1 aamir ngs 2.0M Sep 26 10:51 Cicer_arietinum_GA_v1.0.gene.gtf.gz
-rwxrwx--- 1 aamir ngs 6.6M Sep 25 15:17 Cicer_arietinum_GA_v1.0.gene.pep.fa.gz
-rw-rw-r-- 1 aamir ngs    0 Nov 22 08:45 noncoding.txt
-rw-rw-r-- 1 aamir ngs    0 Nov 22 08:45 protein_coding_genes.txt

SIFT_alignments:
total 0

SIFT_predictions:
total 0

singleRecords:
total 0

singleRecords_with_scores:
total 0

subst:
total 0

v1.0:
total 0

Kindly let me know in case other information is needed

Thank you

Best regards
Aamir

**Comment by rvaser** [comment]
Please run `perl make-single-records-BIOPERL.pl test_files/cicer_arietinum_config.txt` from the same directory you ran `perl make-SIFT-db-all.pl ...` and send me the output/error messages.

Best regards,
Robert

**Comment by pauline-ng** [comment]
Hi Robert and Aamir,

There are 2 bugs here:

1) sift4g isn't working on the example human genome that's included with the installation -- Robert, can you help Aamir with that?

2) the perlscripts aren't producing the appropriate protein files -- I know the scripts for these quite well, so I can assist with this. Aamir, please send me your gff file so I can make sure it's in the right format.

Thanks,
Pauline

**Comment by rvaser** [comment]
Hi Pauline,
the sift4g compiler problem has been addressed and should be solved soon. Thank you for jumping in on the database creation part, I have backtracked the problem to `make-single-records-BIOPERL.pl` script so far.

Best regards,
Robert

**Comment by pauline-ng** [comment]
Hi Aamir,

From the README on creating databases:

"In the gtf file, make sure the 9th column (attribute column) says gene_biotype "protein_coding;" for rows which are labelled as exon, CDS, stop_codon, and start_codon."

For each protein, you'll need to annotate exon, CDS, stop_codon, and start_codon.  The scripts make use of these positions to translate genomic sequence into amino acid sequence.

Thanks,
Pauline

**Comment by aamirwkhan06** [comment]
Dear Pauline and Robert

The sift-4g was compiled with g++ 4.9.4 and the human database compilation has already crossed the step which was throwing error due to old g++.

Log for make-single-records-BIOPERL.pl says "Generating Single Records... takes a long time"

I have attached the cicer_arietinum GFF and GTF files for your reference.

Please suggest to reformat the GFF/GTF files


Thank you

Best regards
Aamir

[Cicer_arietinum_GA_v1.0.gene.gff.tar.gz](https://github.com/rvaser/sift4g/files/1498089/Cicer_arietinum_GA_v1.0.gene.gff.tar.gz)

[Cicer_arietinum_GA_v1.0.gene.gtf.gz](https://github.com/rvaser/sift4g/files/1498099/Cicer_arietinum_GA_v1.0.gene.gtf.gz)

**Comment by pauline-ng** [comment]
Hi Aamir,

I'm closing this thread because the GTF file format thread will be addressed in:
https://github.com/pauline-ng/SIFT4G_Create_Genomic_DB/issues/6

Aamir -- I checked your gft.gz file and it doesn't follow the format that I advised in my previous comment from 14 hours ago. Please get it in that format, and continue to the thread on the SIFT4G_Create_Genomic_DB/issues/6.

Thanks,
Pauline
