### ISSUE TITLE
missing sift4g prediction

### ISSUE THREAD

**Issue by LipengKang** [rvaser/sift4g#5]
Hi, Robert
with pauline's help, sift4g can bring predictions. But still many errors in log file like this:
`Use of uninitialized value $aa in string eq at make-single-records-BIOPERL.pl line 270
Use of uninitialized value $aa in concatenation (.) or string at make-single-records-BIOPERL.pl line 276
Use of uninitialized value $mutated_aa in string eq at make-single-records-BIOPERL.pl line 547.
Use of uninitialized value in concatenation (.) or string at make-single-records-BIOPERL.pl line 301.
Use of uninitialized value $aa2 in string eq at generate-fasta-subst-files-BIOPERL.pl line 615.
Use of uninitialized value $aa2 in string ne at generate-fasta-subst-files-BIOPERL.pl line 620.
Use of uninitialized value $mutated_aa in string eq at generate-fasta-subst-files-BIOPERL.pl line 888.`

It seems sift4g breaks when deal with CDS with "NNNN". For example,
![Picture1](https://user-images.githubusercontent.com/37303616/56031020-e444ed00-5d50-11e9-81ee-20514929bba5.png)

![Picture2](https://user-images.githubusercontent.com/37303616/56031040-eeff8200-5d50-11e9-879a-a9e025ca15ee.png)
[](url)

Maybe I should ignore this transcript. I don't know but any way to resolve these errors?

Thanks,
Lipeng

**Comment by pauline-ng** [comment]
Lipeng,

If you have amino acid sequences like the one above (with too mnay X's and periods), then they may be causing the error. Can you filter those out of the fasta file and then try running SIFT 4G?

**Comment by LipengKang** [comment]
I runned it without filter. will this influence my result? if not, I think it is enough for me because amino acid like this is rare.

**Comment by rvaser** [comment]
Hi Lipeng,
are the perl scripts causing errors or does SIFT4G break without generating predictions?

Sorry for the delayed response.
Best regards,
Robert

**Comment by sandyplus** [comment]
@rvaser 
Hi, Robert, 
I got the same warning:
`Use of uninitialized value in concatenation (.) or string at make-single-records-BIOPERL.pl line 305.`
Any suggestions?

Best regards,
sandy

**Comment by rvaser** [comment]
Hi Sandy,
not sure what is causing this warning in the perl script. @pauline-ng, can you please advise?

Best regards,
Robert

**Comment by pauline-ng** [comment]
Hi Sandy,

I maintain the scripts to build a protein file from genome .fa and a gene file (.gtf or gff) that is eventually fed into sift4g.  The warnings you are seeing are no big deal and I ignore them.

Are there predictions in your SIFT_predictions folder?

If yes, then SIFT 4G has been run successfully. If not, then I can start to help you debug.

Thanks,
Pauline

**Comment by sandyplus** [comment]
@pauline-ng 
Hi, Pauline,

After building database, I cannot find anything in SIFT_predictions and SIFT_alignments.
The log file says:

```bash
Use of uninitialized value $aa2 in string eq at generate-fasta-subst-files-BIOPERL.pl line 621.
Use of uninitialized value $aa2 in string eq at generate-fasta-subst-files-BIOPERL.pl line 621.
Use of uninitialized value $aa2 in string ne at generate-fasta-subst-files-BIOPERL.pl line 626.
done making the fasta sequences
start siftsharp, getting the alignments
/home/shiyong/software/SIFT4G/sift4g/bin/sift4g -d /home/shiyong/database/NCBI/UNIREF90/uniref90.fasta -q ./test_files/Pyrus_bretschneideri/all_prot.fasta --subst ./test_files/Pyrus_bretschneideri/subst --out ./test_files/Pyrus_bretschneideri/SIFT_predictions --sub-results
** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 194 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
```
The file tree of my data looks like ths:
```
Pyrus_bretschneideri
├── all_prot.fasta
├── chr-src
│   ├── directory.index
│   ├── Pyrus_bretschneideri.v191211.dna.fa
├── dbSNP
├── fasta
│   ├── rna0.fasta
│   ├── rna10000.fasta
│   ├── rna998.fasta
│   ├── rna9990.fasta
│   ├── rna9991.fasta
│   ...
│   ├── rna9992.fasta
│   ├── rna9993.fasta
│   ├── rna9994.fasta
│   ├── rna9995.fasta
│   ├── rna9996.fasta
│   ├── rna9997.fasta
│   ├── rna9998.fasta
│   └── rna999.fasta
├── fasta.log
├── gene-annotation-src
│   ├── noncoding.txt
│   ├── protein_coding_genes.txt
│   ├── Pyrus_bretschneideri.v191211.gtf.gz
│   └── Pyrus_bretschneideri.v191211.pep.all.fa.gz
├── invalid.log
├── Log2.txt
├── peptide.log
├── SIFT_alignments
├── SIFT_predictions
├── singleRecords
│   ├── NW_008988039.1.invalidRecords
│   ├── NW_008988039.1.singleRecords
│   ├── NW_008988039.1.singleRecords_noncoding
│   ├── NW_008988039.1.singleRecords_proteins.fa
│   ├── NW_008989849.1.invalidRecords
│   ...
│   ├── NW_008989849.1.singleRecords
│   ├── NW_008989849.1.singleRecords_noncoding
│   ├── NW_008989849.1.singleRecords_proteins.fa
│   ├── NW_008990160.1.invalidRecords
│   ├── NW_008990160.1.singleRecords
│   ├── NW_008990160.1.singleRecords_noncoding
│   └── NW_008990160.1.singleRecords_proteins.fa
├── singleRecords_with_scores
├── subst
│   ├── gene10039.subst
│   ├── gene10102.subst
│   ├── gene10114.subst
│   ├── gene10116.subst
│   ├── gene9555.subst
│   ├── gene9562.subst
│   ├── gene9564.subst
│   ├── gene9576.subst
│   ├── gene9584.subst
│   ├── gene95.subst
│   ├── gene9989.subst
│   ...
│   ├── gene9.subst
│   ├── rna0.subst
│   ├── rna10000.subst
│   ├── rna10001.subst
│   ├── rna9979.subst
│   ├── rna997.subst
│   ├── rna9980.subst
│   ├── rna9981.subst
│   ├── rna9982.subst
│   ├── rna9996.subst
│   ├── rna9997.subst
│   ├── rna9998.subst
│   ├── rna9999.subst
│   ├── rna999.subst
│   ├── rna99.subst
│   └── rna9.subst
└── v191211

10 directories, 111108 files
```
FYI, the Pyrus_bretschneideri_config.txt looks like this:
```bash
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=11
MITO_GENETIC_CODE_TABLENAME=Bacterial, Archaeal and Plant Plastid

PARENT_DIR=./test_files/Pyrus_bretschneideri
ORG=Pyrus_bretschneideri
ORG_VERSION=v191211
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=/home/shiyong/software/SIFT4G/sift4g/bin/sift4g
PROTEIN_DB=/home/shiyong/database/NCBI/UNIREF90/uniref90.fasta

# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord
```

Moreover, one of the fasta shows like this (sorry, I cannot remove all "NNN" fasta, since most of them contain "NNN"):
```
>NW_008990177.1 Pyrus x bretschneideri cultivar Dangshansuli unplaced genomic scaffold, Pbr_v1.0 scaffold134.1.9, whole genome shotgun sequence
 AAATTCAATTTTATATTCGTTTTAAATTAAAACATTATGAGACTAATTCT
 TTTTTATTTATTTTTTTTTTAATGTATATTGTTTATATTGTAATTTATCT
 TATATATTAATATTTATTCTTTTACTATACTATTATGATGTTAATATTAA
 TTATAATTGATAAATGTTATTTATCATTTTTATAACTTATAAATCTTATA
 AATAAANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
 NNNNNCTGCCATTAAAAAGTTATAATAGGTTTTTCGGTTGGATGTGAAAG
 ACATCTATTGTTCAAAATCAATTGTTCTTTACTATTCTCTATCTATTTTT
 TCTCTAAATTAGACTCCAAAAAAAAGGGGGGGGGTTAAAAATCACATAAA
 ATATTAATAAGAATGATAAGGTACACTATGCCAAATAGATTGAAGTTGAT
 aaaaaaaaaaaaaaaaaaaaaagaaaGATTGTCCGTTTTCTTTCTATTTT
 CGTCGTGTTACATTTATACATGTAATAAAAAAATCGAAAAGTTTAATAAA
 CCAACCCTTCTCCCGCTTAATTAAAAAATAAAAAAACTTTAAT

```

Any suggestions?

Best regards,
Sandy

**Comment by pauline-ng** [comment]
Hi Sandy,

Can you send me the website where you downloaded the chromosome and gene file?  

The fasta files should be all protein sequences.   RNA sequences are being generated as well which will break sift4g.

If you send me the website, I'll try to modify the script on my side so as not to generate RNA sequences.

Thanks,
Pauline

**Comment by sandyplus** [comment]
@pauline-ng 
Hi, Pauline,

Thank you for your quick response.
I downloaded the chromosome sequences and gff file from here.
- chromosome_dna: `ftp://ftp.ncbi.nlm.nih.gov/genomes/Pyrus_x_bretschneideri/CHR_Un/225117_ref_Pbr_v1.0_chrUn.fa.gz`
- gff3: `ftp://ftp.ncbi.nlm.nih.gov/genomes/Pyrus_x_bretschneideri/GFF/ref_Pbr_v1.0_top_level.gff3.gz`

>The fasta files should be all protein sequences.

Should I change the DNA sequences to protein sequences (I extracted protein sequences by gffread) in the "chr-src" folder?

>RNA sequences are being generated as well which will break sift4g.

FYI, the rnaxxx.fasta is protein sequences rather than rna sequences. For example, the rna10000.fasta looks like this:
```
>rna10000
MDDQEVFPGANMGGELASSCSMDSFFDDLLKDTHACTHAHTCNPPGPDYSHTHTCFHVHTKILSSASEDKAGTDDTAESGEKKSKKQPLGNKVAVRKYREKEKARVKLLEDEVLNLRAENRRLVMRLQGQPALEAEIARLKCLLVDIRGRIEGEIGSFPYQKSVNPS     LPNPNMPGAIFMNPCNVQCDDQLYCLHPGMDGKCGDGAVMNGQDFNGCGFESLQCFANQDGGAKELPDCGVGNGVSNVNSSGTSKRKRGTRAAAAN
```

Best regards,
Sandy

**Comment by sandyplus** [comment]
Dear Pauline,

I removed all sequences with "NNN". However, the warning still showed up:
```
Use of uninitialized value $fasta_subseq in concatenation (.) or string at generate-fasta-subst-files-BIOPERL.pl line             446, <IN_TX> line 21479.
```

**Comment by pauline-ng** [comment]
@sandyplus 

I was able to generate a database. However, I was unable to replicate your error -- I did not see any RNA sequences in my folders.

1) The file NCBI names in the fasta file do not match the gff file. Hence, you must format the fasta names.
```
cd chr-src
gunzip 225117_ref_Pbr_v1.0_chrUn.fa.gz
cat 225117_ref_Pbr_v1.0_chrUn.fa  | awk -F "|" '{if ($_ ~ /^>/) { print ">" $4} else { print $_}}' > modified_chr.fa
mv 225117_ref_Pbr_v1.0_chrUn.fa 225117_ref_Pbr_v1.0_chrUn.fa_old
```

so that ***chr-src*** directory only has

```
modified_chr.fa.gz
225117_ref_Pbr_v1.0_chrUn.fa 225117_ref_Pbr_v1.0_chrUn.fa_old
```
2) The directory ***gene-annotation-src*** directory should only have

```
ref_Pbr_v1.0_top_level.gene.gtf.gz
ref_Pbr_v1.0_top_level.gff3.gz
```

3) You should have no other files or folders -- the SIFT script will generate the appropriate files.  

Thanks,
Pauline

**Comment by sandyplus** [comment]
@pauline-ng 
Hi, Pauline,
I was still unable to build a database.
I tried to build database of another species. It works. 
But my data failed even use the modified genome fasta as you mentioned.
After 3 days of running, the folder contains:
```bash
├── all_prot.fasta
├── chr-src
│   ├── directory.index
│   └── modified_chr.fa
├── dbSNP
├── fasta
│   ├── rna0.fasta
│   ├── rna10000.fasta
│   ├── rna9982.fasta
│   ├── rna9983.fasta
│   ├── rna9984.fasta
│   ├── rna9985.fasta
│   ├── rna9986.fasta
│   ├── rna9987.fasta
│   ├── rna9988.fasta
│   ├── rna9989.fasta
│   ├── rna998.fasta
│   ├── rna9990.fasta
│   ├── rna9991.fasta
...
│   ├── rna9992.fasta
│   ├── rna9993.fasta
│   ├── rna9994.fasta
│   ├── rna9995.fasta
│   ├── rna9996.fasta
│   ├── rna9997.fasta
│   ├── rna9998.fasta
│   └── rna999.fasta
├── fasta.log
├── gene-annotation-src
│   ├── noncoding.txt
│   ├── protein_coding_genes.txt
│   └── Pyrus_bretschneideri.v191211.gtf.gz
├── invalid.log
├── Log2.txt
├── peptide.log
├── SIFT_alignments
├── SIFT_predictions
├── singleRecords
│   ├── NW_008988039.1.invalidRecords
│   ├── NW_008988039.1.singleRecords
│   ├── NW_008988039.1.singleRecords_noncoding
│   ├── NW_008988039.1.singleRecords_proteins.fa
│   ├── NW_008989822.1.invalidRecords
│   ├── NW_008989822.1.singleRecords
...
│   ├── NW_008989822.1.singleRecords_noncoding
│   ├── NW_008989822.1.singleRecords_proteins.fa
│   ├── NW_008989980.1.singleRecords_noncoding
│   ├── NW_008989985.1.singleRecords_proteins.fa
│   ├── NW_008989988.1.invalidRecords
│   ├── NW_008989988.1.singleRecords
│   ├── NW_008989988.1.singleRecords_noncoding
│   ├── NW_008989988.1.singleRecords_proteins.fa
├── singleRecords_with_scores
├── subst
│   ├── gene10039.subst
│   ├── gene10102.subst
│   ├── gene10114.subst
│   ├── gene9690.subst
│   ├── gene9712.subst
│   ├── gene9713.subst
│   ├── gene9724.subst
│   ├── gene9740.subst
│   ├── gene9970.subst
│   ├── gene9973.subst
...
│   ├── gene9974.subst
│   ├── gene9989.subst
│   ├── gene9.subst
│   ├── rna0.subst
│   ├── rna10000.subst
│   ├── rna10001.subst
│   ├── rna9978.subst
│   ├── rna9979.subst
│   ├── rna997.subst
│   ├── rna99.subst
│   └── rna9.subst
└── v191211

10 directories, 111104 files
```
I produced the gtf file by gffread. Should I make some changes to the gtf file?
Moreover, how can I skip the step of making fasta sequences. 
It took a long time if I run the command again. 
I think it is not necessary because all the fasta files already exist.

Best regards, 
sandy

**Comment by sandyplus** [comment]
Hi, Pauline,
The log file shows it stopped in the "aligning queries":
```bash
entered mkdir ./test_files/Pyrus_bretschneideri_test4/v191211
converting gene format to use-able input
done converting gene format
making single records file
Use of uninitialized value $aa in string eq at make-single-records-BIOPERL.pl line 274.
Use of uninitialized value $aa in concatenation (.) or string at make-single-records-BIOPERL.pl line 280.
Use of uninitialized value $aa in string eq at make-single-records-BIOPERL.pl line 274.
Use of uninitialized value $aa in concatenation (.) or string at make-single-records-BIOPERL.pl line 280.
Use of uninitialized value $orig_aa in string eq at make-single-records-BIOPERL.pl line 551.
Use of uninitialized value $mutated_aa in string eq at make-single-records-BIOPERL.pl line 551.
Use of uninitialized value $orig_aa in string eq at make-single-records-BIOPERL.pl line 551.
Use of uninitialized value $aa2 in string eq at generate-fasta-subst-files-BIOPERL.pl line 621.
Use of uninitialized value $aa2 in string ne at generate-fasta-subst-files-BIOPERL.pl line 626.
done making the fasta sequences
start siftsharp, getting the alignments
/home/shiyong/software/SIFT4G/sift4g/bin/sift4g -d /home/shiyong/database/NCBI/UNIREF90/uniref90.fasta -q ./test_files/Pyrus_bretschneideri_test4/all_prot.fasta --subst ./test_files/Pyrus_bretschneideri_test4/subst --out ./test_files/Pyrus_bretschneideri_test4/SIFT_predictions --sub-results
** Checking query data and substitutions files **
processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
 processing database part 194 (size ~0.25 GB): 100.00/100.00% *

** Aligning queries with candidate sequences **
 processing database part 1 (size ~1.00 GB): 32.50/100.00% *
```
My config file is:
```bash
GENETIC_CODE_TABLE=1
GENETIC_CODE_TABLENAME=Standard
MITO_GENETIC_CODE_TABLE=1
MITO_GENETIC_CODE_TABLENAME=Standard

PARENT_DIR=./test_files/Pyrus_bretschneideri_test4
ORG=Pyrus_bretschneideri
ORG_VERSION=v191211
DBSNP_VCF_FILE=

#Running SIFT 4G
SIFT4G_PATH=/home/shiyong/software/SIFT4G/sift4g/bin/sift4g
PROTEIN_DB=/home/shiyong/database/NCBI/UNIREF90/uniref90.fasta

# Sub-directories, don't need to change
GENE_DOWNLOAD_DEST=gene-annotation-src
CHR_DOWNLOAD_DEST=chr-src
LOGFILE=Log.txt
ZLOGFILE=Log2.txt
FASTA_DIR=fasta
SUBST_DIR=subst
ALIGN_DIR=SIFT_alignments
SIFT_SCORE_DIR=SIFT_predictions
SINGLE_REC_BY_CHR_DIR=singleRecords
SINGLE_REC_WITH_SIFTSCORE_DIR=singleRecords_with_scores
DBSNP_DIR=dbSNP

# Doesn't need to change
FASTA_LOG=fasta.log
INVALID_LOG=invalid.log
PEPTIDE_LOG=peptide.log
ENS_PATTERN=ENS
SINGLE_RECORD_PATTERN=:change:_aa1valid_dbsnp.singleRecord

```
The related commands I used:
```bash
#making GTF:
gffread ref_Pbr_v1.0_top_level.gff3 -T -o Pyrus_bretschneideri.v191211.gtf
#modified fasta name
zcat 225117_ref_Pbr_v1.0_chrUn.fa.gz |awk -F"|" '{if($_ ~ /^>/){ print ">" $4} else { print $_ }}' > modified_chr.fa
#build the database
perl make-SIFT-db-all.pl -config test_files/Pyrus_bretschneideri_test4_config.txt 2>&1 |tee Pyrus_test191217.log
```
Best regards,
Sandy

**Comment by sandyplus** [comment]
Hi, Pauline,
I trimmed my gtf. It works now.
I will do more tests and let you know the results.
Thanks a lot for your help.

Best regards,
Sandy

**Comment by jarobin** [comment]
Hi Sandy,

I think I am having a similar error when I try to build a SIFT database from an Ensembl genome fasta and GTF file. The run dies at: 

** Aligning queries with candidate sequences **
* processing database part 1 (size ~1.00 GB): 22.50/100.00% *

What do you mean when you say that you trimmed your GTF file?

Jacqueline

**Comment by sandyplus** [comment]
> Hi Sandy,
> 
> I think I am having a similar error when I try to build a SIFT database from an Ensembl genome fasta and GTF file. The run dies at:
> 
> ** Aligning queries with candidate sequences **
> 
> * processing database part 1 (size ~1.00 GB): 22.50/100.00% *
> 
> What do you mean when you say that you trimmed your GTF file?
> 
> Jacqueline

I split my protein fasta into multiple files, and test them one by one. Finally, I found some protein cannot be annotated by sift4g. After removing these "bad proteins", I got the results.

Best regards,
Sandy

**Comment by pauline-ng** [comment]
Hi @sandyplus ,

Do you remember what the "bad proteins" looked like? Did they have "X" or "*" in them, for example?

Best,
Pauline

**Comment by Jiangjiangzhang6** [comment]
Chr     Genes with SIFT Scores  Pos with SIFT scores    Pos with Confident Scores
chr1    100 (4564/4581) 100 (8081133/8091534)   47(3811688/8081133)
chr2    100 (6940/6972) 100 (12859616/12875192) 52(6668469/12859616)
chr3    100 (4687/4705) 100 (8429808/8437708)   50(4240741/8429808)
chr4    100 (6129/6147) 100 (11176434/11185382) 50(5552235/11176434)
chr5    100 (5658/5675) 100 (10580045/10588535) 50(5278986/10580045)
chr6    100 (6660/6670) 100 (12601667/12610430) 49(6190420/12601667)
 hello , my check.log
It's show that the last one line was not high, would the database wa created done ? And annotate the vcf with all NA in the result. how did I do with this error?  Thanks .

**Comment by Jiangjiangzhang6** [comment]
> Chr Genes with SIFT Scores Pos with SIFT scores Pos with Confident Scores chr1 100 (4564/4581) 100 (8081133/8091534) 47(3811688/8081133) chr2 100 (6940/6972) 100 (12859616/12875192) 52(6668469/12859616) chr3 100 (4687/4705) 100 (8429808/8437708) 50(4240741/8429808) chr4 100 (6129/6147) 100 (11176434/11185382) 50(5552235/11176434) chr5 100 (5658/5675) 100 (10580045/10588535) 50(5278986/10580045) chr6 100 (6660/6670) 100 (12601667/12610430) 49(6190420/12601667) hello , my check.log It's show that the last one line was not high, would the database wa created done ? And annotate the vcf with all NA in the result. how did I do with this error? Thanks .

scaffold10371   0 (0/0) 0 (0/0) 0(0/0)
scaffold10374   0 (0/0) 0 (0/0) 0(0/0)
scaffold10377   0 (0/0) 0 (0/0) 0(0/0)
scaffold10389   0 (0/0) 0 (0/0) 0(0/0)
scaffold10394   0 (0/0) 0 (0/0) 0(0/0)
scaffold10397   0 (0/0) 0 (0/0) 0(0/0)
scaffold10398   0 (0/0) 0 (0/0) 0(0/0)
scaffold10404   0 (0/0) 0 (0/0) 0(0/0)
scaffold10408   0 (0/0) 0 (0/0) 0(0/0)
scaffold10412   0 (0/0) 0 (0/0) 0(0/0)
scaffold10422   0 (0/0) 0 (0/0) 0(0/0)
scaffold10428   0 (0/0) 0 (0/0) 0(0/0)
scaffold10431   0 (0/0) 0 (0/0) 0(0/0)
and the contig all error, I didn't know why?

**Comment by pauline-ng** [comment]
@Jiangjiangzhang6 You have submitted multiple issues in for SIFT. Please combine them into 1 and create only 1 new issue. It is hard to keep track of the problem/question you're asking.  (Also, please do not hijack other people's issues, especially as your error looks different.)
