### ISSUE TITLE
could not make on linux ( Ubuntu 18.04.2 LTS)

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [rvaser/sift4g#7]
Hi,
    I met a problem when I try to make, and I could not know how to fix it.
    The error is "recipe for target 'obj/database_search.o' failed"
![image](https://user-images.githubusercontent.com/46480129/69034054-4d918a80-0a1b-11ea-9610-ffc3943f3b79.png)
    Could you pleas help me?
Best wishes,
Liu

**Comment by rvaser** [comment]
Hi Liu,
can you please paste the whole error message? Also, please run ```g++ --version``` and paste the output.

Best regards,
Robert

**Comment by ggoodstudydaydayup** [comment]
Hi Robert,
Thanks for your reply. This is the g++ version.
![image](https://user-images.githubusercontent.com/46480129/69038013-ed531680-0a23-11ea-97d3-2c7a89653efd.png)
And when I try to make , there were two errors.
![image](https://user-images.githubusercontent.com/46480129/69038077-15427a00-0a24-11ea-893b-e67297c0353f.png)
"Makefile:39: recipe for target 'obj/database_search.o' failed
make[1]: *** [obj/database_search.o] Error 1
Makefile:20: recipe for target 'sift4g' failed
make: *** [sift4g] Error 2"
Best wishes,
Liu

**Comment by rvaser** [comment]
Try replacing `floor` with `std::floor` in file `src/database_search.cpp` at line 264, and recompile with `make`.

**Comment by ggoodstudydaydayup** [comment]
Hi Robert,
     I try to replacing floor with std::floor,but there was still error. 
     So I try to add #include <math.h>, it works.
     Thanks for your reply.
Best wishes,
Liu
