### ISSUE TITLE
regex_error

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [rvaser/sift4g#8]
Hi,
    I'm not sure why I run the sift4g with this error. 
   "terminate called after throwing an instance of 'std::regex_error'  
     what():  regex_error"
    Could you please tell me?
Best wishes,
Liu

**Comment by rvaser** [comment]
Hello Liu,
which compiler version do you have?

Best regards,
Robert

**Comment by ggoodstudydaydayup** [comment]
Hi Robert,
     My gcc version is  7.3.0.
Best wishes,
Liu

**Comment by rvaser** [comment]
Hmm, this error usually happened with older `gcc` compilers. Can you paste the path of the compiler? Also, try running `/usr/bin/gcc --version`.

**Comment by ggoodstudydaydayup** [comment]
Hi Robert,
      This is my gcc path and version.
![image](https://user-images.githubusercontent.com/46480129/70439072-284be580-1aca-11ea-8e05-ee4f43547db8.png)
![image](https://user-images.githubusercontent.com/46480129/70439100-3568d480-1aca-11ea-8f85-4969afcf5fef.png)
       Thanks.
Liu

**Comment by rvaser** [comment]
I think that the Makefile picks up the older version. Try editing the first line of [this Makefile](https://github.com/rvaser/sift4g/blob/master/sift4g/Makefile). Replace `g++` with `~/01Script/miniconda3/bin/g++` (install g++ in the miniconda environment if you do not have it). Or look if you have a newer compiler in /usr/bin/ (`g++-<int>`). If so, just replace g++ with `g++-<int>`.

**Comment by ggoodstudydaydayup** [comment]
Hi Robert,
I change the Makefile, but there were nothing changed.
Is that right about my result after make ?
![image](https://user-images.githubusercontent.com/46480129/70439818-cbe9c580-1acb-11ea-9960-aedca17de815.png)
Thanks,
Liu

**Comment by rvaser** [comment]
You have to run `make clean` and recompile with `make`.

**Comment by ggoodstudydaydayup** [comment]
![image](https://user-images.githubusercontent.com/46480129/70439999-2aaf3f00-1acc-11ea-916b-4ffc483b9f91.png)
There is the result, should I change  -03 to -g ?

**Comment by rvaser** [comment]
Hmm, what does `g++ --version` say?

**Comment by ggoodstudydaydayup** [comment]
I'm sorry to reply the g++ -- version. I replace g++ with ~/01Script/miniconda3/bin/g++ . The g++ version of conda is  7.3.0.  My /usr/bin/g++ --version is 4.8.5 .

**Comment by rvaser** [comment]
Is the above error the only one? I am not sure what is the cause.

**Comment by ggoodstudydaydayup** [comment]
>>> sift4g <<<
[CP] src/sift_prediction.cpp
g++: error: unrecognized command line option '-03'
make[1]: *** [Makefile:41: obj/sift_prediction.o] Error 1
make: *** [Makefile:21: sift4g] Error 2

This is the information.

**Comment by ggoodstudydaydayup** [comment]
Hi Robert,
I'm sorry about my mistake last time when I change the makefile. 
Now it works after I replace the -03 with -O3,and then replace the floor() with float() in the src/database_search.cpp.
Thanks very much.
Liu

**Comment by rvaser** [comment]
Oh okay. `float()` and `floor()` do different things. Revert this change and add `#include <math.h>` to `src/database_search.cpp` file.

**Comment by ggoodstudydaydayup** [comment]
It works well.
Thanks very much. 
Liu
