### ISSUE TITLE
Missing swsharp dependency? 

### ISSUE THREAD

**Issue by apredeus** [rvaser/sift4g#9]
Hello Robert, 

I've tried to compile the `sift4g` code, and it seems to fail because swsharp headers are missing. Probably got lost somewhere along the way? ;)

> [CP] src/sift_prediction.cpp
> In file included from src/sift_prediction.cpp:16:
> src/sift_scores.hpp:17:10: fatal error: swsharp/swsharp.h: No such file or directory
>  #include "swsharp/swsharp.h"
>           ^~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:41: obj/sift_prediction.o] Error 1

**Comment by rvaser** [comment]
Hi Allex,
did you by any chance forgot to add `--recursive` to your `git clone` command?

Best regards,
Robert

**Comment by apredeus** [comment]
No - just double-checked. Ran just like in the readme, and it's still happening.

**Comment by rvaser** [comment]
I copy/pasted the commands from readme and it works for me.

**Comment by apredeus** [comment]
Ok, I realized what my mistake was. I typed `make` in sift4g/sift4g subdirectory instead of the main repo :D

sorry about it, and thank you very much for quick replies.

**Comment by rvaser** [comment]
No problem :)
